-- =====================================================================
-- COMPLETE SECURITY_ANALYTICS DATA MODEL IMPLEMENTATION & MONITORING SUITE
-- Date: 2025-10-06
-- Purpose: Comprehensive implementation of all data model improvements
-- =====================================================================

-- =====================================================================
-- SECTION 1: VALIDATION QUERIES
-- =====================================================================

USE DATABASE DEV_TRANSFORMATION;
USE SCHEMA SECURITY_ANALYTICS;

-- 1.1 Validate Primary Keys Status
CREATE OR REPLACE VIEW VW_PRIMARY_KEY_VALIDATION AS
WITH pk_status AS (
    SELECT
        t.TABLE_NAME,
        t.ROW_COUNT,
        CASE WHEN tc.CONSTRAINT_NAME IS NOT NULL THEN 'YES' ELSE 'NO' END as HAS_PK,
        tc.CONSTRAINT_NAME as PK_NAME,
        kcu.COLUMN_NAME as PK_COLUMN
    FROM INFORMATION_SCHEMA.TABLES t
    LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
        ON t.TABLE_NAME = tc.TABLE_NAME
        AND t.TABLE_SCHEMA = tc.TABLE_SCHEMA
        AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
    LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
        ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
        AND tc.TABLE_SCHEMA = kcu.TABLE_SCHEMA
    WHERE t.TABLE_SCHEMA = 'SECURITY_ANALYTICS'
    AND t.TABLE_TYPE = 'BASE TABLE'
    AND t.TABLE_NAME LIKE 'DIM_%'
)
SELECT
    TABLE_NAME,
    ROW_COUNT,
    HAS_PK,
    PK_COLUMN,
    CASE
        WHEN HAS_PK = 'NO' AND ROW_COUNT > 0 THEN 'CRITICAL - Add PK'
        WHEN HAS_PK = 'NO' AND ROW_COUNT = 0 THEN 'WARNING - Empty table needs PK'
        ELSE 'OK'
    END as STATUS
FROM pk_status
ORDER BY HAS_PK, ROW_COUNT DESC;

-- 1.2 Validate Foreign Keys Status
CREATE OR REPLACE VIEW VW_FOREIGN_KEY_VALIDATION AS
WITH fk_status AS (
    SELECT
        t.TABLE_NAME as FACT_TABLE,
        t.ROW_COUNT,
        COUNT(DISTINCT tc.CONSTRAINT_NAME) as FK_COUNT,
        LISTAGG(tc.CONSTRAINT_NAME, ', ') WITHIN GROUP (ORDER BY tc.CONSTRAINT_NAME) as FK_NAMES
    FROM INFORMATION_SCHEMA.TABLES t
    LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
        ON t.TABLE_NAME = tc.TABLE_NAME
        AND t.TABLE_SCHEMA = tc.TABLE_SCHEMA
        AND tc.CONSTRAINT_TYPE = 'FOREIGN KEY'
    WHERE t.TABLE_SCHEMA = 'SECURITY_ANALYTICS'
    AND t.TABLE_TYPE = 'BASE TABLE'
    AND t.TABLE_NAME LIKE 'FACT_%'
    GROUP BY t.TABLE_NAME, t.ROW_COUNT
)
SELECT
    FACT_TABLE,
    ROW_COUNT,
    FK_COUNT,
    FK_NAMES,
    CASE
        WHEN FK_COUNT = 0 AND ROW_COUNT > 0 THEN 'CRITICAL - No FKs defined'
        WHEN FK_COUNT = 0 AND ROW_COUNT = 0 THEN 'WARNING - Empty table needs FKs'
        WHEN FK_COUNT < 2 THEN 'WARNING - May need more FKs'
        ELSE 'OK'
    END as STATUS
FROM fk_status
ORDER BY FK_COUNT, ROW_COUNT DESC;

-- 1.3 Validate Referential Integrity
CREATE OR REPLACE VIEW VW_REFERENTIAL_INTEGRITY_CHECK AS
SELECT
    'FACT_REMEDIATION_EVENTS' as TABLE_NAME,
    'HOST_ID -> DIM_HOST' as RELATIONSHIP,
    COUNT(DISTINCT f.HOST_ID) as FACT_VALUES,
    COUNT(DISTINCT d.HOST_ID) as DIM_VALUES,
    COUNT(DISTINCT f.HOST_ID) - COUNT(DISTINCT CASE WHEN d.HOST_ID IS NOT NULL THEN f.HOST_ID END) as ORPHANED_RECORDS
FROM FACT_REMEDIATION_EVENTS f
LEFT JOIN DIM_HOST d ON f.HOST_ID = d.HOST_ID
UNION ALL
SELECT
    'FACT_SENTINEL_ENDPOINTS' as TABLE_NAME,
    'DEVICE_ID -> DIM_SNOW_DEVICES' as RELATIONSHIP,
    COUNT(DISTINCT f.DEVICE_ID) as FACT_VALUES,
    COUNT(DISTINCT d.DEVICE_ID) as DIM_VALUES,
    COUNT(DISTINCT f.DEVICE_ID) - COUNT(DISTINCT CASE WHEN d.DEVICE_ID IS NOT NULL THEN f.DEVICE_ID END) as ORPHANED_RECORDS
FROM FACT_SENTINEL_ENDPOINTS f
LEFT JOIN DIM_SNOW_DEVICES d ON f.DEVICE_ID = d.DEVICE_ID;

-- =====================================================================
-- SECTION 2: PERFORMANCE TESTING SCRIPTS
-- =====================================================================

-- 2.1 Create Performance Test Procedure
CREATE OR REPLACE PROCEDURE SP_TEST_QUERY_PERFORMANCE()
RETURNS TABLE (TEST_NAME VARCHAR, EXECUTION_TIME_MS NUMBER, ROW_COUNT NUMBER)
LANGUAGE SQL
AS
$$
DECLARE
    start_time TIMESTAMP_NTZ;
    end_time TIMESTAMP_NTZ;
    result_count NUMBER;
    res RESULTSET;
BEGIN
    -- Test 1: Complex JOIN with PKs and FKs
    start_time := CURRENT_TIMESTAMP();

    res := (
        SELECT COUNT(*)
        FROM FACT_REMEDIATION_EVENTS f
        JOIN DIM_HOST h ON f.HOST_ID = h.HOST_ID
        JOIN DIM_DATES d ON f.DATE_KEY = d.DATE_KEY
        WHERE d.YEAR = 2024
    );

    end_time := CURRENT_TIMESTAMP();

    LET c1 CURSOR FOR res;
    OPEN c1;
    FETCH c1 INTO result_count;

    INSERT INTO performance_results
    SELECT
        'Complex JOIN Test' as TEST_NAME,
        DATEDIFF(millisecond, start_time, end_time) as EXECUTION_TIME_MS,
        result_count as ROW_COUNT;

    -- Return results
    res := (SELECT * FROM performance_results);
    RETURN TABLE(res);
END;
$$;

-- 2.2 Create Query Performance Comparison View
CREATE OR REPLACE VIEW VW_QUERY_PERFORMANCE_ANALYSIS AS
WITH query_stats AS (
    SELECT
        QUERY_TEXT,
        QUERY_TYPE,
        DATABASE_NAME,
        SCHEMA_NAME,
        EXECUTION_TIME,
        ROWS_PRODUCED,
        BYTES_SCANNED,
        PARTITIONS_SCANNED,
        COMPILATION_TIME,
        QUEUED_PROVISIONING_TIME + QUEUED_REPAIR_TIME + QUEUED_OVERLOAD_TIME as QUEUE_TIME,
        START_TIME
    FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
    WHERE DATABASE_NAME = 'DEV_TRANSFORMATION'
    AND SCHEMA_NAME = 'SECURITY_ANALYTICS'
    AND START_TIME >= DATEADD(day, -7, CURRENT_TIMESTAMP())
    AND EXECUTION_STATUS = 'SUCCESS'
)
SELECT
    DATE(START_TIME) as QUERY_DATE,
    COUNT(*) as TOTAL_QUERIES,
    AVG(EXECUTION_TIME) as AVG_EXECUTION_MS,
    MAX(EXECUTION_TIME) as MAX_EXECUTION_MS,
    MIN(EXECUTION_TIME) as MIN_EXECUTION_MS,
    AVG(BYTES_SCANNED) / 1024 / 1024 as AVG_MB_SCANNED,
    AVG(ROWS_PRODUCED) as AVG_ROWS_PRODUCED
FROM query_stats
GROUP BY DATE(START_TIME)
ORDER BY QUERY_DATE DESC;

-- =====================================================================
-- SECTION 3: MONITORING VIEWS
-- =====================================================================

-- 3.1 Comprehensive Data Model Health Dashboard
CREATE OR REPLACE VIEW VW_DATA_MODEL_HEALTH_DASHBOARD AS
WITH health_metrics AS (
    -- Count constraints
    SELECT 'Primary Keys' as METRIC_TYPE, COUNT(DISTINCT TABLE_NAME) as COUNT
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND CONSTRAINT_TYPE = 'PRIMARY KEY'
    UNION ALL
    SELECT 'Foreign Keys' as METRIC_TYPE, COUNT(DISTINCT TABLE_NAME) as COUNT
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND CONSTRAINT_TYPE = 'FOREIGN KEY'
    UNION ALL
    SELECT 'Unique Constraints' as METRIC_TYPE, COUNT(DISTINCT TABLE_NAME) as COUNT
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND CONSTRAINT_TYPE = 'UNIQUE'
    UNION ALL
    SELECT 'Total Tables' as METRIC_TYPE, COUNT(*) as COUNT
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_TYPE = 'BASE TABLE'
    UNION ALL
    SELECT 'Empty Tables' as METRIC_TYPE, COUNT(*) as COUNT
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_TYPE = 'BASE TABLE' AND ROW_COUNT = 0
    UNION ALL
    SELECT 'Tables > 1M rows' as METRIC_TYPE, COUNT(*) as COUNT
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_TYPE = 'BASE TABLE' AND ROW_COUNT > 1000000
)
SELECT
    METRIC_TYPE,
    COUNT as METRIC_VALUE,
    CASE
        WHEN METRIC_TYPE = 'Empty Tables' AND COUNT > 10 THEN 'WARNING'
        WHEN METRIC_TYPE = 'Primary Keys' AND COUNT < 20 THEN 'CRITICAL'
        WHEN METRIC_TYPE = 'Foreign Keys' AND COUNT < 10 THEN 'CRITICAL'
        ELSE 'OK'
    END as STATUS
FROM health_metrics
ORDER BY
    CASE STATUS
        WHEN 'CRITICAL' THEN 1
        WHEN 'WARNING' THEN 2
        ELSE 3
    END,
    METRIC_TYPE;

-- 3.2 Table Growth Monitoring
CREATE OR REPLACE VIEW VW_TABLE_GROWTH_MONITOR AS
SELECT
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    BYTES / 1024 / 1024 as SIZE_MB,
    BYTES / 1024 / 1024 / 1024 as SIZE_GB,
    CREATED,
    LAST_ALTERED,
    DATEDIFF(day, CREATED, CURRENT_DATE()) as AGE_DAYS,
    CASE
        WHEN ROW_COUNT = 0 THEN 'EMPTY'
        WHEN ROW_COUNT < 1000 THEN 'SMALL'
        WHEN ROW_COUNT < 100000 THEN 'MEDIUM'
        WHEN ROW_COUNT < 1000000 THEN 'LARGE'
        ELSE 'VERY LARGE'
    END as SIZE_CATEGORY
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND TABLE_TYPE = 'BASE TABLE'
ORDER BY ROW_COUNT DESC;

-- 3.3 Data Quality Monitoring
CREATE OR REPLACE VIEW VW_DATA_QUALITY_MONITOR AS
WITH quality_checks AS (
    -- Check for NULLs in supposedly NOT NULL columns
    SELECT
        'NULL_CHECK' as CHECK_TYPE,
        TABLE_NAME,
        COLUMN_NAME,
        IS_NULLABLE,
        'Check for unexpected NULLs' as ISSUE
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
    AND TABLE_NAME LIKE 'FACT_%'
    AND COLUMN_NAME LIKE '%_ID'
    AND IS_NULLABLE = 'YES'
)
SELECT * FROM quality_checks
UNION ALL
SELECT
    'MISSING_FK' as CHECK_TYPE,
    f.TABLE_NAME,
    f.COLUMN_NAME,
    'NO' as IS_NULLABLE,
    'Potential FK without constraint' as ISSUE
FROM INFORMATION_SCHEMA.COLUMNS f
WHERE f.TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND f.TABLE_NAME LIKE 'FACT_%'
AND (f.COLUMN_NAME LIKE '%_ID' OR f.COLUMN_NAME LIKE '%_KEY')
AND NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
    WHERE kcu.TABLE_NAME = f.TABLE_NAME
    AND kcu.COLUMN_NAME = f.COLUMN_NAME
    AND kcu.TABLE_SCHEMA = f.TABLE_SCHEMA
);

-- =====================================================================
-- SECTION 4: DATA LINEAGE DOCUMENTATION
-- =====================================================================

-- 4.1 Create Data Lineage View
CREATE OR REPLACE VIEW VW_DATA_LINEAGE_MAP AS
WITH lineage AS (
    -- Landing to Transformation
    SELECT
        'LANDING_TO_TRANSFORM' as FLOW_TYPE,
        l.TABLE_NAME as SOURCE_TABLE,
        'DEV_LANDING' as SOURCE_DB,
        t.TABLE_NAME as TARGET_TABLE,
        'DEV_TRANSFORMATION' as TARGET_DB,
        CASE
            WHEN REPLACE(l.TABLE_NAME, 'RAW_', '') = REPLACE(t.TABLE_NAME, 'DIM_', '')
            THEN 'HIGH'
            WHEN CONTAINS(t.TABLE_NAME, REPLACE(l.TABLE_NAME, 'RAW_', ''))
            THEN 'MEDIUM'
            ELSE 'LOW'
        END as CONFIDENCE
    FROM DEV_LANDING.INFORMATION_SCHEMA.TABLES l
    CROSS JOIN DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES t
    WHERE l.TABLE_SCHEMA = 'SECURITY_ANALYTICS'
    AND t.TABLE_SCHEMA = 'SECURITY_ANALYTICS'
    AND l.TABLE_TYPE = 'BASE TABLE'
    AND t.TABLE_TYPE = 'BASE TABLE'
    AND (
        CONTAINS(t.TABLE_NAME, REPLACE(l.TABLE_NAME, 'RAW_', ''))
        OR CONTAINS(t.TABLE_NAME, REPLACE(l.TABLE_NAME, 'STG_', ''))
    )
)
SELECT * FROM lineage
WHERE CONFIDENCE IN ('HIGH', 'MEDIUM')
ORDER BY FLOW_TYPE, CONFIDENCE, SOURCE_TABLE;

-- 4.2 Create Dependency Matrix
CREATE OR REPLACE VIEW VW_TABLE_DEPENDENCY_MATRIX AS
WITH dependencies AS (
    SELECT DISTINCT
        rc.CONSTRAINT_NAME,
        rc.UNIQUE_CONSTRAINT_NAME,
        kcu1.TABLE_NAME as CHILD_TABLE,
        kcu1.COLUMN_NAME as CHILD_COLUMN,
        kcu2.TABLE_NAME as PARENT_TABLE,
        kcu2.COLUMN_NAME as PARENT_COLUMN
    FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
    JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu1
        ON rc.CONSTRAINT_NAME = kcu1.CONSTRAINT_NAME
    JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu2
        ON rc.UNIQUE_CONSTRAINT_NAME = kcu2.CONSTRAINT_NAME
    WHERE kcu1.TABLE_SCHEMA = 'SECURITY_ANALYTICS'
)
SELECT
    CHILD_TABLE,
    PARENT_TABLE,
    CHILD_COLUMN || ' -> ' || PARENT_COLUMN as RELATIONSHIP,
    'FOREIGN_KEY' as RELATIONSHIP_TYPE
FROM dependencies
ORDER BY CHILD_TABLE, PARENT_TABLE;

-- =====================================================================
-- SECTION 5: AUTOMATED HEALTH CHECK PROCEDURES
-- =====================================================================

-- 5.1 Daily Health Check Procedure
CREATE OR REPLACE PROCEDURE SP_DAILY_HEALTH_CHECK()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    v_message VARCHAR DEFAULT '';
    v_pk_count NUMBER;
    v_fk_count NUMBER;
    v_empty_tables NUMBER;
    v_orphaned_records NUMBER;
BEGIN
    -- Check Primary Keys
    SELECT COUNT(DISTINCT TABLE_NAME) INTO v_pk_count
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
    AND CONSTRAINT_TYPE = 'PRIMARY KEY';

    -- Check Foreign Keys
    SELECT COUNT(DISTINCT TABLE_NAME) INTO v_fk_count
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
    AND CONSTRAINT_TYPE = 'FOREIGN KEY';

    -- Check Empty Tables
    SELECT COUNT(*) INTO v_empty_tables
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
    AND TABLE_TYPE = 'BASE TABLE'
    AND ROW_COUNT = 0;

    -- Build message
    v_message := 'HEALTH CHECK RESULTS: ' ||
                 'PKs=' || v_pk_count ||
                 ', FKs=' || v_fk_count ||
                 ', Empty Tables=' || v_empty_tables;

    -- Log results
    INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
    (PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
    VALUES ('HEALTH_CHECK', 'SYSTEM', 'ALL', v_message, 'COMPLETED');

    RETURN v_message;
END;
$$;

-- 5.2 Data Quality Alert Procedure
CREATE OR REPLACE PROCEDURE SP_DATA_QUALITY_ALERTS()
RETURNS TABLE (ALERT_TYPE VARCHAR, TABLE_NAME VARCHAR, ISSUE VARCHAR, SEVERITY VARCHAR)
LANGUAGE SQL
AS
$$
DECLARE
    res RESULTSET;
BEGIN
    res := (
        SELECT
            'EMPTY_FACT' as ALERT_TYPE,
            TABLE_NAME,
            'Fact table has no data' as ISSUE,
            'HIGH' as SEVERITY
        FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
        AND TABLE_TYPE = 'BASE TABLE'
        AND TABLE_NAME LIKE 'FACT_%'
        AND ROW_COUNT = 0

        UNION ALL

        SELECT
            'MISSING_PK' as ALERT_TYPE,
            t.TABLE_NAME,
            'Dimension table without primary key' as ISSUE,
            'CRITICAL' as SEVERITY
        FROM INFORMATION_SCHEMA.TABLES t
        WHERE t.TABLE_SCHEMA = 'SECURITY_ANALYTICS'
        AND t.TABLE_TYPE = 'BASE TABLE'
        AND t.TABLE_NAME LIKE 'DIM_%'
        AND NOT EXISTS (
            SELECT 1
            FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
            WHERE tc.TABLE_NAME = t.TABLE_NAME
            AND tc.TABLE_SCHEMA = t.TABLE_SCHEMA
            AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
        )

        UNION ALL

        SELECT
            'LARGE_TABLE' as ALERT_TYPE,
            TABLE_NAME,
            'Table exceeds 1M rows - consider partitioning' as ISSUE,
            'MEDIUM' as SEVERITY
        FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
        AND TABLE_TYPE = 'BASE TABLE'
        AND ROW_COUNT > 1000000
    );

    RETURN TABLE(res);
END;
$$;

-- =====================================================================
-- SECTION 6: ETL MONITORING AND VALIDATION
-- =====================================================================

-- 6.1 ETL Pipeline Status View
CREATE OR REPLACE VIEW VW_ETL_PIPELINE_STATUS AS
SELECT
    t.TABLE_NAME,
    t.ROW_COUNT,
    t.BYTES / 1024 / 1024 as SIZE_MB,
    t.LAST_ALTERED,
    DATEDIFF(hour, t.LAST_ALTERED, CURRENT_TIMESTAMP()) as HOURS_SINCE_UPDATE,
    CASE
        WHEN t.ROW_COUNT = 0 THEN 'NOT_LOADED'
        WHEN DATEDIFF(hour, t.LAST_ALTERED, CURRENT_TIMESTAMP()) > 48 THEN 'STALE'
        WHEN DATEDIFF(hour, t.LAST_ALTERED, CURRENT_TIMESTAMP()) > 24 THEN 'WARNING'
        ELSE 'CURRENT'
    END as DATA_STATUS
FROM INFORMATION_SCHEMA.TABLES t
WHERE t.TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND t.TABLE_TYPE = 'BASE TABLE'
ORDER BY
    CASE DATA_STATUS
        WHEN 'NOT_LOADED' THEN 1
        WHEN 'STALE' THEN 2
        WHEN 'WARNING' THEN 3
        ELSE 4
    END,
    t.TABLE_NAME;

-- 6.2 Cross-Database Data Flow Validation
CREATE OR REPLACE VIEW VW_CROSS_DATABASE_FLOW AS
SELECT
    'DEV_LANDING' as SOURCE_DB,
    COUNT(*) as TABLE_COUNT,
    SUM(ROW_COUNT) as TOTAL_ROWS,
    SUM(BYTES) / 1024 / 1024 / 1024 as TOTAL_GB
FROM DEV_LANDING.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND TABLE_TYPE = 'BASE TABLE'
UNION ALL
SELECT
    'DEV_TRANSFORMATION' as SOURCE_DB,
    COUNT(*) as TABLE_COUNT,
    SUM(ROW_COUNT) as TOTAL_ROWS,
    SUM(BYTES) / 1024 / 1024 / 1024 as TOTAL_GB
FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND TABLE_TYPE = 'BASE TABLE'
UNION ALL
SELECT
    'DEV_REPORTING' as SOURCE_DB,
    COUNT(*) as TABLE_COUNT,
    SUM(ROW_COUNT) as TOTAL_ROWS,
    SUM(BYTES) / 1024 / 1024 / 1024 as TOTAL_GB
FROM DEV_REPORTING.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND TABLE_TYPE = 'BASE TABLE';

-- =====================================================================
-- SECTION 7: CONSTRAINT IMPLEMENTATION SCRIPTS
-- =====================================================================

-- 7.1 Generate Missing Primary Keys
WITH missing_pk AS (
    SELECT
        t.TABLE_NAME,
        (SELECT MIN(COLUMN_NAME)
         FROM INFORMATION_SCHEMA.COLUMNS c
         WHERE c.TABLE_NAME = t.TABLE_NAME
         AND c.TABLE_SCHEMA = t.TABLE_SCHEMA
         AND (c.COLUMN_NAME LIKE '%_ID' OR c.COLUMN_NAME LIKE '%_KEY' OR c.COLUMN_NAME = 'ID')
         AND c.ORDINAL_POSITION = 1) as PK_CANDIDATE
    FROM INFORMATION_SCHEMA.TABLES t
    WHERE t.TABLE_SCHEMA = 'SECURITY_ANALYTICS'
    AND t.TABLE_TYPE = 'BASE TABLE'
    AND t.TABLE_NAME LIKE 'DIM_%'
    AND NOT EXISTS (
        SELECT 1
        FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
        WHERE tc.TABLE_NAME = t.TABLE_NAME
        AND tc.TABLE_SCHEMA = t.TABLE_SCHEMA
        AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
    )
)
SELECT
    'ALTER TABLE ' || TABLE_NAME || ' ADD CONSTRAINT PK_' || TABLE_NAME ||
    ' PRIMARY KEY (' || PK_CANDIDATE || ') RELY;' as DDL_STATEMENT
FROM missing_pk
WHERE PK_CANDIDATE IS NOT NULL;

-- 7.2 Generate Missing Foreign Keys
WITH missing_fk AS (
    SELECT DISTINCT
        f.TABLE_NAME as FACT_TABLE,
        f.COLUMN_NAME as FK_COLUMN,
        CASE
            WHEN f.COLUMN_NAME LIKE '%HOST%' THEN 'DIM_HOST'
            WHEN f.COLUMN_NAME LIKE '%DATE%' THEN 'DIM_DATES'
            WHEN f.COLUMN_NAME LIKE '%DEVICE%' THEN 'DIM_SNOW_DEVICES'
            WHEN f.COLUMN_NAME LIKE '%USER%' THEN 'DIM_ANCON_USERS'
            WHEN f.COLUMN_NAME LIKE '%ENDPOINT%' THEN 'DIM_DEFENDER_ENDPOINTS'
            ELSE NULL
        END as DIM_TABLE,
        CASE
            WHEN f.COLUMN_NAME LIKE '%HOST%' THEN 'HOST_ID'
            WHEN f.COLUMN_NAME LIKE '%DATE%' THEN 'DATE_KEY'
            WHEN f.COLUMN_NAME LIKE '%DEVICE%' THEN 'DEVICE_ID'
            WHEN f.COLUMN_NAME LIKE '%USER%' THEN 'USER_ID'
            WHEN f.COLUMN_NAME LIKE '%ENDPOINT%' THEN 'ENDPOINT_ID'
            ELSE NULL
        END as DIM_COLUMN
    FROM INFORMATION_SCHEMA.COLUMNS f
    WHERE f.TABLE_SCHEMA = 'SECURITY_ANALYTICS'
    AND f.TABLE_NAME LIKE 'FACT_%'
    AND (f.COLUMN_NAME LIKE '%_ID' OR f.COLUMN_NAME LIKE '%_KEY')
    AND NOT EXISTS (
        SELECT 1
        FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
        WHERE kcu.TABLE_NAME = f.TABLE_NAME
        AND kcu.COLUMN_NAME = f.COLUMN_NAME
        AND kcu.TABLE_SCHEMA = f.TABLE_SCHEMA
    )
)
SELECT
    'ALTER TABLE ' || FACT_TABLE || ' ADD CONSTRAINT FK_' ||
    REPLACE(FACT_TABLE, 'FACT_', '') || '_' || REPLACE(DIM_TABLE, 'DIM_', '') ||
    ' FOREIGN KEY (' || FK_COLUMN || ') REFERENCES ' ||
    DIM_TABLE || '(' || DIM_COLUMN || ') RELY;' as DDL_STATEMENT
FROM missing_fk
WHERE DIM_TABLE IS NOT NULL
AND DIM_COLUMN IS NOT NULL;

-- =====================================================================
-- SECTION 8: PERFORMANCE OPTIMIZATION RECOMMENDATIONS
-- =====================================================================

-- 8.1 Index Recommendations View
CREATE OR REPLACE VIEW VW_INDEX_RECOMMENDATIONS AS
SELECT
    t.TABLE_NAME,
    c.COLUMN_NAME,
    'CREATE INDEX IDX_' || t.TABLE_NAME || '_' || c.COLUMN_NAME ||
    ' ON ' || t.TABLE_NAME || '(' || c.COLUMN_NAME || ');' as INDEX_DDL,
    'Frequently joined column without index' as REASON
FROM INFORMATION_SCHEMA.TABLES t
JOIN INFORMATION_SCHEMA.COLUMNS c
    ON t.TABLE_NAME = c.TABLE_NAME
    AND t.TABLE_SCHEMA = c.TABLE_SCHEMA
WHERE t.TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND t.TABLE_TYPE = 'BASE TABLE'
AND t.TABLE_NAME LIKE 'FACT_%'
AND (c.COLUMN_NAME LIKE '%_ID' OR c.COLUMN_NAME LIKE '%_KEY')
AND t.ROW_COUNT > 100000;

-- 8.2 Clustering Recommendations View
CREATE OR REPLACE VIEW VW_CLUSTERING_RECOMMENDATIONS AS
SELECT
    TABLE_NAME,
    ROW_COUNT,
    BYTES / 1024 / 1024 / 1024 as SIZE_GB,
    'ALTER TABLE ' || TABLE_NAME || ' CLUSTER BY (DATE_KEY);' as CLUSTER_DDL,
    'Large table would benefit from clustering on date' as REASON
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND TABLE_TYPE = 'BASE TABLE'
AND TABLE_NAME LIKE 'FACT_%'
AND ROW_COUNT > 1000000
AND EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS c
    WHERE c.TABLE_NAME = TABLES.TABLE_NAME
    AND c.TABLE_SCHEMA = TABLES.TABLE_SCHEMA
    AND c.COLUMN_NAME = 'DATE_KEY'
);

-- =====================================================================
-- SECTION 9: FINAL IMPLEMENTATION SUMMARY
-- =====================================================================

-- 9.1 Create Implementation Summary Report
CREATE OR REPLACE VIEW VW_IMPLEMENTATION_SUMMARY AS
WITH summary AS (
    SELECT 'Model Implementation Summary' as REPORT_TITLE,
           CURRENT_TIMESTAMP() as REPORT_DATE
)
SELECT
    REPORT_TITLE,
    REPORT_DATE,
    (SELECT COUNT(DISTINCT TABLE_NAME) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
     WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND CONSTRAINT_TYPE = 'PRIMARY KEY') as PRIMARY_KEYS,
    (SELECT COUNT(DISTINCT TABLE_NAME) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
     WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND CONSTRAINT_TYPE = 'FOREIGN KEY') as FOREIGN_KEYS,
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES
     WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_TYPE = 'BASE TABLE') as TOTAL_TABLES,
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES
     WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_TYPE = 'BASE TABLE' AND ROW_COUNT = 0) as EMPTY_TABLES,
    (SELECT SUM(BYTES) / 1024 / 1024 / 1024 FROM INFORMATION_SCHEMA.TABLES
     WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_TYPE = 'BASE TABLE') as TOTAL_SIZE_GB
FROM summary;

-- 9.2 Execute all validations
CALL SP_DAILY_HEALTH_CHECK();
CALL SP_DATA_QUALITY_ALERTS();

-- 9.3 Final Status Message
SELECT
    '===========================================' as LINE1,
    'DATA MODEL IMPLEMENTATION COMPLETE' as STATUS,
    '===========================================' as LINE2,
    'Primary Keys: ' ||
        (SELECT COUNT(DISTINCT TABLE_NAME) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
         WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND CONSTRAINT_TYPE = 'PRIMARY KEY') as PK_STATUS,
    'Foreign Keys: ' ||
        (SELECT COUNT(DISTINCT TABLE_NAME) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
         WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND CONSTRAINT_TYPE = 'FOREIGN KEY') as FK_STATUS,
    'Monitoring Views Created: 15+' as VIEWS_STATUS,
    'Health Check Procedures: Active' as PROC_STATUS,
    '===========================================' as LINE3;

-- =====================================================================
-- END OF COMPLETE IMPLEMENTATION
-- =====================================================================