-- Run this script as ACCOUNTADMIN to activate the tasks

USE ROLE ACCOUNTADMIN;
USE DATABASE DEV_TRANSFORMATION;
USE SCHEMA SECURITY_ANALYTICS;

-- Grant EXECUTE TASK privilege to DEV_DEVELOPER role
GRANT EXECUTE TASK ON ACCOUNT TO ROLE DEV_DEVELOPER;

-- Switch back to DEV_DEVELOPER and activate tasks
USE ROLE DEV_DEVELOPER;

ALTER TASK TASK_DAILY_HEALTH_CHECK RESUME;
ALTER TASK TASK_DATA_QUALITY_MONITOR RESUME;
ALTER TASK TASK_ETL_PIPELINE_MONITOR RESUME;

-- Verify tasks are running
SHOW TASKS IN SCHEMA SECURITY_ANALYTICS;
