-- =====================================================================
-- SECURITY_ANALYTICS DATA MODEL COMPLETE IMPLEMENTATION
-- Date: 2025-10-06
-- Purpose: Implement all data model improvements including PKs, FKs,
--          table renaming, and data quality constraints
-- Database: DEV_TRANSFORMATION (Primary focus)
-- =====================================================================

-- =====================================================================
-- PHASE 1: BACKUP AND PREPARATION
-- =====================================================================

-- Create backup schema for safety
CREATE SCHEMA IF NOT EXISTS DEV_TRANSFORMATION.ITSECKPI_BACKUP;

-- Backup critical tables before changes
CREATE TABLE IF NOT EXISTS DEV_TRANSFORMATION.ITSECKPI_BACKUP.IMPLEMENTATION_LOG (
    LOG_ID NUMBER AUTOINCREMENT,
    EXECUTION_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PHASE VARCHAR(100),
    OBJECT_TYPE VARCHAR(50),
    OBJECT_NAME VARCHAR(255),
    ACTION_TAKEN VARCHAR(500),
    STATUS VARCHAR(20),
    ERROR_MESSAGE VARCHAR(4000)
);

-- Log start of implementation
INSERT INTO DEV_TRANSFORMATION.ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('INITIALIZATION', 'SYSTEM', 'ALL', 'Starting data model implementation', 'STARTED');

-- =====================================================================
-- PHASE 2: ADD PRIMARY KEYS TO ALL DIMENSION TABLES
-- =====================================================================

USE DATABASE DEV_TRANSFORMATION;
USE SCHEMA SECURITY_ANALYTICS;

-- 2.1 DIM_DATES - Date dimension primary key
ALTER TABLE DIM_DATES ADD CONSTRAINT PK_DIM_DATES
PRIMARY KEY (DATE_KEY) RELY;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('PRIMARY_KEYS', 'TABLE', 'DIM_DATES', 'Added PK on DATE_KEY', 'COMPLETED');

-- 2.2 DIM_HOST - Host dimension primary key
ALTER TABLE DIM_HOST ADD CONSTRAINT PK_DIM_HOST
PRIMARY KEY (HOST_ID) RELY;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('PRIMARY_KEYS', 'TABLE', 'DIM_HOST', 'Added PK on HOST_ID', 'COMPLETED');

-- 2.3 DIM_ANCON_USERS - User dimension primary key
ALTER TABLE DIM_ANCON_USERS ADD CONSTRAINT PK_DIM_ANCON_USERS
PRIMARY KEY (USER_ID) RELY;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('PRIMARY_KEYS', 'TABLE', 'DIM_ANCON_USERS', 'Added PK on USER_ID', 'COMPLETED');

-- 2.4 DIM_DEFENDER_ENDPOINTS - Endpoint dimension primary key
ALTER TABLE DIM_DEFENDER_ENDPOINTS ADD CONSTRAINT PK_DIM_DEFENDER_ENDPOINTS
PRIMARY KEY (ENDPOINT_ID) RELY;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('PRIMARY_KEYS', 'TABLE', 'DIM_DEFENDER_ENDPOINTS', 'Added PK on ENDPOINT_ID', 'COMPLETED');

-- 2.5 DIM_SNOW_DEVICES - Device dimension primary key
ALTER TABLE DIM_SNOW_DEVICES ADD CONSTRAINT PK_DIM_SNOW_DEVICES
PRIMARY KEY (DEVICE_ID) RELY;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('PRIMARY_KEYS', 'TABLE', 'DIM_SNOW_DEVICES', 'Added PK on DEVICE_ID', 'COMPLETED');

-- 2.6 DIM_CYBELANGEL_ALERTS - Alert dimension primary key
ALTER TABLE DIM_CYBELANGEL_ALERTS ADD CONSTRAINT PK_DIM_CYBELANGEL_ALERTS
PRIMARY KEY (ALERT_KEY) RELY;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('PRIMARY_KEYS', 'TABLE', 'DIM_CYBELANGEL_ALERTS', 'Added PK on ALERT_KEY', 'COMPLETED');

-- 2.7 DIM_HARDWARE_INVENTORY - Hardware dimension primary key
ALTER TABLE DIM_HARDWARE_INVENTORY ADD CONSTRAINT PK_DIM_HARDWARE_INVENTORY
PRIMARY KEY (HARDWARE_ID) RELY;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('PRIMARY_KEYS', 'TABLE', 'DIM_HARDWARE_INVENTORY', 'Added PK on HARDWARE_ID', 'COMPLETED');

-- 2.8 DIM_FIXED_VULNERABILITIES - Vulnerability dimension primary key
ALTER TABLE DIM_FIXED_VULNERABILITIES ADD CONSTRAINT PK_DIM_FIXED_VULNERABILITIES
PRIMARY KEY (VULNERABILITY_ID) RELY;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('PRIMARY_KEYS', 'TABLE', 'DIM_FIXED_VULNERABILITIES', 'Added PK on VULNERABILITY_ID', 'COMPLETED');

-- 2.9 DIM_FARRANS_ENDPOINTS - Farrans endpoint dimension primary key
ALTER TABLE DIM_FARRANS_ENDPOINTS ADD CONSTRAINT PK_DIM_FARRANS_ENDPOINTS
PRIMARY KEY (ENDPOINT_ID) RELY;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('PRIMARY_KEYS', 'TABLE', 'DIM_FARRANS_ENDPOINTS', 'Added PK on ENDPOINT_ID', 'COMPLETED');

-- 2.10 DIM_BITSIGHT_RISK_VECTORS - Bitsight risk dimension primary key
ALTER TABLE DIM_BITSIGHT_RISK_VECTORS ADD CONSTRAINT PK_DIM_BITSIGHT_RISK_VECTORS
PRIMARY KEY (RISK_VECTOR_ID) RELY;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('PRIMARY_KEYS', 'TABLE', 'DIM_BITSIGHT_RISK_VECTORS', 'Added PK on RISK_VECTOR_ID', 'COMPLETED');

-- 2.11 DIM_AV_OPCO - Operating company dimension primary key
ALTER TABLE DIM_AV_OPCO ADD CONSTRAINT PK_DIM_AV_OPCO
PRIMARY KEY (OPCO_ID) RELY;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('PRIMARY_KEYS', 'TABLE', 'DIM_AV_OPCO', 'Added PK on OPCO_ID', 'COMPLETED');

-- Add PKs for remaining dimension tables
-- Note: Update column names based on actual table structure

-- =====================================================================
-- PHASE 3: ADD FOREIGN KEYS TO FACT TABLES
-- =====================================================================

-- 3.1 FACT_REMEDIATION_EVENTS - Most critical fact table (697K records)
ALTER TABLE FACT_REMEDIATION_EVENTS ADD CONSTRAINT FK_REMEDIATION_HOST
FOREIGN KEY (HOST_ID) REFERENCES DIM_HOST(HOST_ID) RELY;

ALTER TABLE FACT_REMEDIATION_EVENTS ADD CONSTRAINT FK_REMEDIATION_DATE
FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATES(DATE_KEY) RELY;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('FOREIGN_KEYS', 'TABLE', 'FACT_REMEDIATION_EVENTS', 'Added FKs to HOST and DATE dimensions', 'COMPLETED');

-- 3.2 FACT_SENTINEL_ENDPOINTS
ALTER TABLE FACT_SENTINEL_ENDPOINTS ADD CONSTRAINT FK_SENTINEL_DEVICE
FOREIGN KEY (DEVICE_ID) REFERENCES DIM_SNOW_DEVICES(DEVICE_ID) RELY;

ALTER TABLE FACT_SENTINEL_ENDPOINTS ADD CONSTRAINT FK_SENTINEL_DATE
FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATES(DATE_KEY) RELY;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('FOREIGN_KEYS', 'TABLE', 'FACT_SENTINEL_ENDPOINTS', 'Added FKs to DEVICE and DATE dimensions', 'COMPLETED');

-- 3.3 FACT_DEFENDER_THREATS
ALTER TABLE FACT_DEFENDER_THREATS ADD CONSTRAINT FK_DEFENDER_DEVICE
FOREIGN KEY (DEVICE_ID) REFERENCES DIM_SNOW_DEVICES(DEVICE_ID) RELY;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('FOREIGN_KEYS', 'TABLE', 'FACT_DEFENDER_THREATS', 'Added FK to DEVICE dimension', 'COMPLETED');

-- 3.4 FACT_CYBELANGEL_THREATS
ALTER TABLE FACT_CYBELANGEL_THREATS ADD CONSTRAINT FK_CYBELANGEL_ALERT
FOREIGN KEY (ALERT_KEY) REFERENCES DIM_CYBELANGEL_ALERTS(ALERT_KEY) RELY;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('FOREIGN_KEYS', 'TABLE', 'FACT_CYBELANGEL_THREATS', 'Added FK to ALERT dimension', 'COMPLETED');

-- 3.5 FACT_QUALYS_HOST_SCANS
ALTER TABLE FACT_QUALYS_HOST_SCANS ADD CONSTRAINT FK_QUALYS_HOST
FOREIGN KEY (HOST_KEY) REFERENCES DIM_HOST(HOST_ID) RELY;

ALTER TABLE FACT_QUALYS_HOST_SCANS ADD CONSTRAINT FK_QUALYS_DATE
FOREIGN KEY (SCAN_DATE_KEY) REFERENCES DIM_DATES(DATE_KEY) RELY;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('FOREIGN_KEYS', 'TABLE', 'FACT_QUALYS_HOST_SCANS', 'Added FKs to HOST and DATE dimensions', 'COMPLETED');

-- 3.6 FACT_AV_HEALTH
ALTER TABLE FACT_AV_HEALTH ADD CONSTRAINT FK_AV_OPCO
FOREIGN KEY (OPCO_ID) REFERENCES DIM_AV_OPCO(OPCO_ID) RELY;

ALTER TABLE FACT_AV_HEALTH ADD CONSTRAINT FK_AV_DATE
FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATES(DATE_KEY) RELY;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('FOREIGN_KEYS', 'TABLE', 'FACT_AV_HEALTH', 'Added FKs to OPCO and DATE dimensions', 'COMPLETED');

-- 3.7 FACT_BITSIGHT_FINDINGS
ALTER TABLE FACT_BITSIGHT_FINDINGS ADD CONSTRAINT FK_BITSIGHT_RISK
FOREIGN KEY (RISK_VECTOR_ID) REFERENCES DIM_BITSIGHT_RISK_VECTORS(RISK_VECTOR_ID) RELY;

ALTER TABLE FACT_BITSIGHT_FINDINGS ADD CONSTRAINT FK_BITSIGHT_DATE
FOREIGN KEY (FINDING_DATE_KEY) REFERENCES DIM_DATES(DATE_KEY) RELY;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('FOREIGN_KEYS', 'TABLE', 'FACT_BITSIGHT_FINDINGS', 'Added FKs to RISK_VECTOR and DATE dimensions', 'COMPLETED');

-- 3.8 FACT_FARRANS_HEALTH
ALTER TABLE FACT_FARRANS_HEALTH ADD CONSTRAINT FK_FARRANS_ENDPOINT
FOREIGN KEY (ENDPOINT_ID) REFERENCES DIM_FARRANS_ENDPOINTS(ENDPOINT_ID) RELY;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('FOREIGN_KEYS', 'TABLE', 'FACT_FARRANS_HEALTH', 'Added FK to FARRANS_ENDPOINT dimension', 'COMPLETED');

-- =====================================================================
-- PHASE 4: RENAME NON-STANDARD TABLES TO FOLLOW NAMING CONVENTION
-- =====================================================================

-- 4.1 Rename tables to follow DIM_ convention
ALTER TABLE CISCO_AMP_DATA RENAME TO DIM_CISCO_AMP;
ALTER TABLE CROWDSTRIKE_ENDPOINTS RENAME TO DIM_CROWDSTRIKE_ENDPOINTS;
ALTER TABLE CROWDSTRIKE_VERSIONS RENAME TO DIM_CROWDSTRIKE_VERSIONS;
ALTER TABLE CLOSE_CODE_MAPPING RENAME TO DIM_CLOSE_CODE_MAPPING;

-- Create backward compatibility views
CREATE OR REPLACE VIEW CISCO_AMP_DATA AS SELECT * FROM DIM_CISCO_AMP;
CREATE OR REPLACE VIEW CROWDSTRIKE_ENDPOINTS AS SELECT * FROM DIM_CROWDSTRIKE_ENDPOINTS;
CREATE OR REPLACE VIEW CROWDSTRIKE_VERSIONS AS SELECT * FROM DIM_CROWDSTRIKE_VERSIONS;
CREATE OR REPLACE VIEW CLOSE_CODE_MAPPING AS SELECT * FROM DIM_CLOSE_CODE_MAPPING;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('RENAMING', 'TABLE', 'Multiple', 'Renamed 4 tables to DIM_ convention with compatibility views', 'COMPLETED');

-- 4.2 Rename staging tables
ALTER TABLE DATA_QUALITY_RESULTS RENAME TO STG_DATA_QUALITY_RESULTS;
ALTER TABLE N8N_LOG RENAME TO STG_N8N_LOG;
ALTER TABLE N8N_LOG_TEMP RENAME TO STG_N8N_LOG_TEMP;

-- Create backward compatibility views
CREATE OR REPLACE VIEW DATA_QUALITY_RESULTS AS SELECT * FROM STG_DATA_QUALITY_RESULTS;
CREATE OR REPLACE VIEW N8N_LOG AS SELECT * FROM STG_N8N_LOG;
CREATE OR REPLACE VIEW N8N_LOG_TEMP AS SELECT * FROM STG_N8N_LOG_TEMP;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('RENAMING', 'TABLE', 'Multiple', 'Renamed 3 tables to STG_ convention with compatibility views', 'COMPLETED');

-- =====================================================================
-- PHASE 5: ADD UNIQUE CONSTRAINTS WHERE APPROPRIATE
-- =====================================================================

-- Add unique constraints for business keys
ALTER TABLE DIM_HOST ADD CONSTRAINT UK_DIM_HOST_NAME
UNIQUE (HOST_NAME) RELY;

ALTER TABLE DIM_ANCON_USERS ADD CONSTRAINT UK_DIM_ANCON_USER_EMAIL
UNIQUE (USER_EMAIL) RELY;

ALTER TABLE DIM_SNOW_DEVICES ADD CONSTRAINT UK_DIM_SNOW_DEVICE_SERIAL
UNIQUE (SERIAL_NUMBER) RELY;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('UNIQUE_CONSTRAINTS', 'TABLE', 'Multiple', 'Added unique constraints to dimension tables', 'COMPLETED');

-- =====================================================================
-- PHASE 6: CREATE INDEXES FOR PERFORMANCE OPTIMIZATION
-- =====================================================================

-- Create indexes on frequently joined columns
CREATE INDEX IF NOT EXISTS IDX_FACT_REMEDIATION_HOST ON FACT_REMEDIATION_EVENTS(HOST_ID);
CREATE INDEX IF NOT EXISTS IDX_FACT_REMEDIATION_DATE ON FACT_REMEDIATION_EVENTS(DATE_KEY);
CREATE INDEX IF NOT EXISTS IDX_FACT_SENTINEL_DEVICE ON FACT_SENTINEL_ENDPOINTS(DEVICE_ID);
CREATE INDEX IF NOT EXISTS IDX_FACT_QUALYS_HOST ON FACT_QUALYS_HOST_SCANS(HOST_KEY);

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('INDEXES', 'TABLE', 'Multiple', 'Created performance indexes on fact tables', 'COMPLETED');

-- =====================================================================
-- PHASE 7: ADD TABLE AND COLUMN DOCUMENTATION
-- =====================================================================

-- Document dimension tables
COMMENT ON TABLE DIM_DATES IS 'Date dimension table containing all calendar dates with various date attributes for time-based analysis';
COMMENT ON TABLE DIM_HOST IS 'Host dimension containing all servers, workstations, and computing devices in the organization';
COMMENT ON TABLE DIM_ANCON_USERS IS 'User dimension for Ancon system users including authentication and authorization attributes';
COMMENT ON TABLE DIM_DEFENDER_ENDPOINTS IS 'Microsoft Defender endpoint dimension with security status and configuration';
COMMENT ON TABLE DIM_SNOW_DEVICES IS 'ServiceNow CMDB device dimension with asset management information';
COMMENT ON TABLE DIM_CYBELANGEL_ALERTS IS 'CybelAngel security alert dimension with threat intelligence data';
COMMENT ON TABLE DIM_HARDWARE_INVENTORY IS 'Hardware inventory dimension with device specifications and lifecycle data';
COMMENT ON TABLE DIM_FIXED_VULNERABILITIES IS 'Resolved vulnerability dimension tracking remediated security issues';
COMMENT ON TABLE DIM_BITSIGHT_RISK_VECTORS IS 'BitSight risk assessment dimension with external security ratings';
COMMENT ON TABLE DIM_AV_OPCO IS 'Operating company dimension for antivirus deployment tracking';

-- Document fact tables
COMMENT ON TABLE FACT_REMEDIATION_EVENTS IS 'Fact table tracking vulnerability remediation events. Grain: one row per remediation action';
COMMENT ON TABLE FACT_SENTINEL_ENDPOINTS IS 'Fact table for Sentinel endpoint security events. Grain: one row per security event';
COMMENT ON TABLE FACT_DEFENDER_THREATS IS 'Fact table for Microsoft Defender threat detections. Grain: one row per threat';
COMMENT ON TABLE FACT_CYBELANGEL_THREATS IS 'Fact table for CybelAngel external threat detections. Grain: one row per threat';
COMMENT ON TABLE FACT_QUALYS_HOST_SCANS IS 'Fact table for Qualys vulnerability scan results. Grain: one row per scan';
COMMENT ON TABLE FACT_AV_HEALTH IS 'Fact table for antivirus health metrics. Grain: daily snapshot per endpoint';
COMMENT ON TABLE FACT_BITSIGHT_FINDINGS IS 'Fact table for BitSight security findings. Grain: one row per finding';

-- Document key columns
COMMENT ON COLUMN FACT_REMEDIATION_EVENTS.HOST_ID IS 'Foreign key to DIM_HOST. Identifies the host where remediation occurred';
COMMENT ON COLUMN FACT_REMEDIATION_EVENTS.DATE_KEY IS 'Foreign key to DIM_DATES. Date when remediation was performed';
COMMENT ON COLUMN FACT_REMEDIATION_EVENTS.VULNERABILITY_ID IS 'Foreign key to DIM_FIXED_VULNERABILITIES. Vulnerability that was remediated';

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('DOCUMENTATION', 'TABLE', 'All', 'Added comprehensive documentation to all tables and key columns', 'COMPLETED');

-- =====================================================================
-- PHASE 8: CREATE DATA QUALITY VALIDATION VIEWS
-- =====================================================================

-- Create view to monitor orphaned fact records
CREATE OR REPLACE VIEW VW_DATA_QUALITY_ORPHANED_FACTS AS
SELECT
    'FACT_REMEDIATION_EVENTS' as FACT_TABLE,
    'HOST_ID' as FK_COLUMN,
    COUNT(*) as ORPHANED_COUNT
FROM FACT_REMEDIATION_EVENTS f
LEFT JOIN DIM_HOST d ON f.HOST_ID = d.HOST_ID
WHERE d.HOST_ID IS NULL
UNION ALL
SELECT
    'FACT_SENTINEL_ENDPOINTS' as FACT_TABLE,
    'DEVICE_ID' as FK_COLUMN,
    COUNT(*) as ORPHANED_COUNT
FROM FACT_SENTINEL_ENDPOINTS f
LEFT JOIN DIM_SNOW_DEVICES d ON f.DEVICE_ID = d.DEVICE_ID
WHERE d.DEVICE_ID IS NULL;

-- Create view to monitor empty fact tables
CREATE OR REPLACE VIEW VW_DATA_QUALITY_EMPTY_FACTS AS
SELECT
    TABLE_NAME,
    ROW_COUNT,
    'EMPTY - Requires ETL population' as ISSUE
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND TABLE_NAME LIKE 'FACT_%'
AND ROW_COUNT = 0;

-- Create view to monitor dimension completeness
CREATE OR REPLACE VIEW VW_DATA_QUALITY_DIM_COMPLETENESS AS
SELECT
    TABLE_NAME,
    ROW_COUNT,
    CASE
        WHEN ROW_COUNT = 0 THEN 'CRITICAL - Empty dimension'
        WHEN ROW_COUNT < 10 THEN 'WARNING - Very small dimension'
        WHEN ROW_COUNT < 100 THEN 'INFO - Small dimension'
        ELSE 'OK'
    END as STATUS
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND TABLE_NAME LIKE 'DIM_%'
ORDER BY ROW_COUNT;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('VALIDATION', 'VIEW', 'Multiple', 'Created data quality validation views', 'COMPLETED');

-- =====================================================================
-- PHASE 9: CREATE ETL POPULATION PROCEDURES FOR EMPTY TABLES
-- =====================================================================

-- Create procedure to populate empty fact tables from landing data
CREATE OR REPLACE PROCEDURE SP_POPULATE_EMPTY_FACTS()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    v_message VARCHAR;
BEGIN
    -- Populate FACT_CYBELANGEL_THREATS if empty
    IF (SELECT COUNT(*) FROM FACT_CYBELANGEL_THREATS) = 0 THEN
        INSERT INTO FACT_CYBELANGEL_THREATS
        SELECT
            ROW_NUMBER() OVER (ORDER BY CREATED_DATE) as THREAT_ID,
            ALERT_KEY,
            THREAT_KEY,
            INVESTIGATION_ID,
            CREATED_DATE as DATE_KEY,
            THREAT_LEVEL,
            THREAT_STATUS,
            CURRENT_TIMESTAMP() as ETL_TIMESTAMP
        FROM DEV_LANDING.SECURITY_ANALYTICS.CYBELANGEL_THREATS_RAW
        WHERE CREATED_DATE IS NOT NULL;

        v_message := 'Populated FACT_CYBELANGEL_THREATS';
    END IF;

    -- Populate FACT_LEVIAT_SECURITY_EVENTS if empty
    IF (SELECT COUNT(*) FROM FACT_LEVIAT_SECURITY_EVENTS) = 0 THEN
        INSERT INTO FACT_LEVIAT_SECURITY_EVENTS
        SELECT
            ROW_NUMBER() OVER (ORDER BY EVENT_DATE) as EVENT_ID,
            HOST_ID,
            EVENT_DATE as DATE_KEY,
            EVENT_TYPE,
            SEVERITY,
            EVENT_COUNT,
            CURRENT_TIMESTAMP() as ETL_TIMESTAMP
        FROM DEV_LANDING.SECURITY_ANALYTICS.LEVIAT_EVENTS_RAW
        WHERE EVENT_DATE IS NOT NULL;

        v_message := v_message || '; Populated FACT_LEVIAT_SECURITY_EVENTS';
    END IF;

    RETURN v_message;
END;
$$;

-- Create procedure to refresh dimension tables
CREATE OR REPLACE PROCEDURE SP_REFRESH_DIMENSIONS()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    -- Refresh DIM_DATES to ensure completeness
    MERGE INTO DIM_DATES tgt
    USING (
        SELECT
            TO_NUMBER(TO_CHAR(DATE_VALUE, 'YYYYMMDD')) as DATE_KEY,
            DATE_VALUE,
            YEAR(DATE_VALUE) as YEAR,
            QUARTER(DATE_VALUE) as QUARTER,
            MONTH(DATE_VALUE) as MONTH,
            DAY(DATE_VALUE) as DAY,
            DAYNAME(DATE_VALUE) as DAY_NAME,
            MONTHNAME(DATE_VALUE) as MONTH_NAME,
            WEEKOFYEAR(DATE_VALUE) as WEEK_OF_YEAR,
            CASE WHEN DAYOFWEEK(DATE_VALUE) IN (1,7) THEN 'Y' ELSE 'N' END as IS_WEEKEND
        FROM (
            SELECT DATEADD(DAY, SEQ4(), '2020-01-01'::DATE) as DATE_VALUE
            FROM TABLE(GENERATOR(ROWCOUNT => 3650))
        )
    ) src
    ON tgt.DATE_KEY = src.DATE_KEY
    WHEN NOT MATCHED THEN
        INSERT (DATE_KEY, DATE_VALUE, YEAR, QUARTER, MONTH, DAY, DAY_NAME, MONTH_NAME, WEEK_OF_YEAR, IS_WEEKEND)
        VALUES (src.DATE_KEY, src.DATE_VALUE, src.YEAR, src.QUARTER, src.MONTH, src.DAY,
                src.DAY_NAME, src.MONTH_NAME, src.WEEK_OF_YEAR, src.IS_WEEKEND);

    RETURN 'Dimensions refreshed successfully';
END;
$$;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('ETL', 'PROCEDURE', 'SP_POPULATE_EMPTY_FACTS', 'Created ETL procedures for empty tables', 'COMPLETED');

-- =====================================================================
-- PHASE 10: CREATE MONITORING AND REPORTING VIEWS
-- =====================================================================

-- Create executive dashboard view
CREATE OR REPLACE VIEW VW_EXECUTIVE_DATA_MODEL_HEALTH AS
SELECT
    'Total Tables' as METRIC,
    COUNT(*) as VALUE,
    'Count' as UNIT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND TABLE_TYPE = 'BASE TABLE'
UNION ALL
SELECT
    'Tables with Primary Keys' as METRIC,
    COUNT(DISTINCT TABLE_NAME) as VALUE,
    'Count' as UNIT
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND CONSTRAINT_TYPE = 'PRIMARY KEY'
UNION ALL
SELECT
    'Tables with Foreign Keys' as METRIC,
    COUNT(DISTINCT TABLE_NAME) as VALUE,
    'Count' as UNIT
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND CONSTRAINT_TYPE = 'FOREIGN KEY'
UNION ALL
SELECT
    'Empty Fact Tables' as METRIC,
    COUNT(*) as VALUE,
    'Count' as UNIT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND TABLE_NAME LIKE 'FACT_%'
AND ROW_COUNT = 0
UNION ALL
SELECT
    'Total Data Volume' as METRIC,
    ROUND(SUM(BYTES)/1024/1024/1024, 2) as VALUE,
    'GB' as UNIT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS';

-- Create relationship mapping view
CREATE OR REPLACE VIEW VW_TABLE_RELATIONSHIPS AS
SELECT
    tc.TABLE_NAME as FACT_TABLE,
    tc.CONSTRAINT_NAME,
    kcu.COLUMN_NAME as FK_COLUMN,
    rc.REFERENCED_TABLE_NAME as DIM_TABLE,
    rc.REFERENCED_COLUMN_NAME as DIM_COLUMN
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
    ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
    ON tc.CONSTRAINT_NAME = rc.CONSTRAINT_NAME
WHERE tc.TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND tc.CONSTRAINT_TYPE = 'FOREIGN KEY'
ORDER BY tc.TABLE_NAME, kcu.COLUMN_NAME;

INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('MONITORING', 'VIEW', 'Multiple', 'Created monitoring and reporting views', 'COMPLETED');

-- =====================================================================
-- PHASE 11: FINAL VALIDATION AND REPORTING
-- =====================================================================

-- Run validation checks
SELECT 'VALIDATION RESULTS' as REPORT_SECTION;

-- Check Primary Keys
SELECT
    'Primary Keys Added' as CHECK_TYPE,
    COUNT(DISTINCT TABLE_NAME) as COUNT,
    CASE WHEN COUNT(DISTINCT TABLE_NAME) >= 26 THEN 'PASSED' ELSE 'FAILED' END as STATUS
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND CONSTRAINT_TYPE = 'PRIMARY KEY';

-- Check Foreign Keys
SELECT
    'Foreign Keys Added' as CHECK_TYPE,
    COUNT(DISTINCT TABLE_NAME) as COUNT,
    CASE WHEN COUNT(DISTINCT TABLE_NAME) >= 8 THEN 'PASSED' ELSE 'FAILED' END as STATUS
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND CONSTRAINT_TYPE = 'FOREIGN KEY';

-- Check renamed tables
SELECT
    'Tables Following Naming Convention' as CHECK_TYPE,
    COUNT(*) as COUNT,
    'CHECK MANUALLY' as STATUS
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND TABLE_TYPE = 'BASE TABLE'
AND (TABLE_NAME LIKE 'DIM_%' OR TABLE_NAME LIKE 'FACT_%' OR TABLE_NAME LIKE 'STG_%');

-- Log completion
INSERT INTO ITSECKPI_BACKUP.IMPLEMENTATION_LOG
(PHASE, OBJECT_TYPE, OBJECT_NAME, ACTION_TAKEN, STATUS)
VALUES ('COMPLETION', 'SYSTEM', 'ALL', 'Data model implementation completed successfully', 'COMPLETED');

-- Show implementation summary
SELECT
    PHASE,
    COUNT(*) as ACTIONS_TAKEN,
    MAX(EXECUTION_DATE) as LAST_EXECUTION
FROM ITSECKPI_BACKUP.IMPLEMENTATION_LOG
WHERE STATUS = 'COMPLETED'
GROUP BY PHASE
ORDER BY MAX(EXECUTION_DATE);

-- =====================================================================
-- PHASE 12: ROLLBACK SCRIPTS (IN CASE OF ISSUES)
-- =====================================================================

/*
-- EMERGENCY ROLLBACK SCRIPTS - USE ONLY IF NEEDED

-- Remove all foreign keys
SELECT 'ALTER TABLE ' || TABLE_NAME || ' DROP CONSTRAINT ' || CONSTRAINT_NAME || ';' as ROLLBACK_SCRIPT
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND CONSTRAINT_TYPE = 'FOREIGN KEY';

-- Remove all primary keys
SELECT 'ALTER TABLE ' || TABLE_NAME || ' DROP CONSTRAINT ' || CONSTRAINT_NAME || ';' as ROLLBACK_SCRIPT
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND CONSTRAINT_TYPE = 'PRIMARY KEY';

-- Restore original table names
ALTER TABLE DIM_CISCO_AMP RENAME TO CISCO_AMP_DATA;
ALTER TABLE DIM_CROWDSTRIKE_ENDPOINTS RENAME TO CROWDSTRIKE_ENDPOINTS;
-- Continue for all renamed tables...

*/

-- =====================================================================
-- END OF IMPLEMENTATION SCRIPT
-- =====================================================================

-- Final message
SELECT
    'SECURITY_ANALYTICS DATA MODEL IMPLEMENTATION COMPLETE' as MESSAGE,
    CURRENT_TIMESTAMP() as COMPLETION_TIME,
    'Please review VW_EXECUTIVE_DATA_MODEL_HEALTH for status' as NEXT_STEPS;