-- ============================================================================
-- Upload utils.py and database.py WITHOUT compression to all 18 apps
-- ============================================================================

-- Set context
USE WAREHOUSE DEV_WH;
USE DATABASE DEV_REPORTING;
USE SCHEMA SECURITY_ANALYTICS;

-- Ancon
PUT file://utils.py @STREAMLIT_APPS_STAGE/Ancon/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://database.py @STREAMLIT_APPS_STAGE/Ancon/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- BitSight
PUT file://utils.py @STREAMLIT_APPS_STAGE/BitSight/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://database.py @STREAMLIT_APPS_STAGE/BitSight/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Cisco_AMP
PUT file://utils.py @STREAMLIT_APPS_STAGE/Cisco_AMP/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://database.py @STREAMLIT_APPS_STAGE/Cisco_AMP/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Crowdstrike
PUT file://utils.py @STREAMLIT_APPS_STAGE/Crowdstrike/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://database.py @STREAMLIT_APPS_STAGE/Crowdstrike/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- CybelAngel
PUT file://utils.py @STREAMLIT_APPS_STAGE/CybelAngel/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://database.py @STREAMLIT_APPS_STAGE/CybelAngel/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Intel_Threats
PUT file://utils.py @STREAMLIT_APPS_STAGE/Intel_Threats/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://database.py @STREAMLIT_APPS_STAGE/Intel_Threats/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Leviat
PUT file://utils.py @STREAMLIT_APPS_STAGE/Leviat/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://database.py @STREAMLIT_APPS_STAGE/Leviat/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Proofpoint
PUT file://utils.py @STREAMLIT_APPS_STAGE/Proofpoint/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://database.py @STREAMLIT_APPS_STAGE/Proofpoint/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Qualys
PUT file://utils.py @STREAMLIT_APPS_STAGE/Qualys/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://database.py @STREAMLIT_APPS_STAGE/Qualys/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- SentinelOne
PUT file://utils.py @STREAMLIT_APPS_STAGE/SentinelOne/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://database.py @STREAMLIT_APPS_STAGE/SentinelOne/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- ServiceNow
PUT file://utils.py @STREAMLIT_APPS_STAGE/ServiceNow/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://database.py @STREAMLIT_APPS_STAGE/ServiceNow/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Sophos
PUT file://utils.py @STREAMLIT_APPS_STAGE/Sophos/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://database.py @STREAMLIT_APPS_STAGE/Sophos/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Splunk
PUT file://utils.py @STREAMLIT_APPS_STAGE/Splunk/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://database.py @STREAMLIT_APPS_STAGE/Splunk/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Symantec
PUT file://utils.py @STREAMLIT_APPS_STAGE/Symantec/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://database.py @STREAMLIT_APPS_STAGE/Symantec/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Tenable
PUT file://utils.py @STREAMLIT_APPS_STAGE/Tenable/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://database.py @STREAMLIT_APPS_STAGE/Tenable/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Trellix
PUT file://utils.py @STREAMLIT_APPS_STAGE/Trellix/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://database.py @STREAMLIT_APPS_STAGE/Trellix/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Zerofox
PUT file://utils.py @STREAMLIT_APPS_STAGE/Zerofox/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://database.py @STREAMLIT_APPS_STAGE/Zerofox/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Zscaler
PUT file://utils.py @STREAMLIT_APPS_STAGE/Zscaler/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://database.py @STREAMLIT_APPS_STAGE/Zscaler/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Verify upload
LIST @STREAMLIT_APPS_STAGE/Sophos/;
