-- Check structures of tables causing view failures

USE ROLE DEV_DEVELOPER;
USE WAREHOUSE DEV_WH;
USE DATABASE DEV_TRANSFORMATION;
USE SCHEMA SECURITY_ANALYTICS;

-- Check DATA_QUALITY_SCORECARD structure
SELECT '=== DATA_QUALITY_SCORECARD ===' AS TABLE_INFO;
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND TABLE_NAME = 'DATA_QUALITY_SCORECARD'
ORDER BY ORDINAL_POSITION;

-- Check ETL_PIPELINE_LOG structure
SELECT '=== ETL_PIPELINE_LOG ===' AS TABLE_INFO;
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND TABLE_NAME = 'ETL_PIPELINE_LOG'
ORDER BY ORDINAL_POSITION;

-- Check FACT_EDR structure
SELECT '=== FACT_EDR ===' AS TABLE_INFO;
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND TABLE_NAME = 'FACT_EDR'
ORDER BY ORDINAL_POSITION;

-- Check DATA_LINEAGE_CATALOG structure
SELECT '=== DATA_LINEAGE_CATALOG ===' AS TABLE_INFO;
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND TABLE_NAME = 'DATA_LINEAGE_CATALOG'
ORDER BY ORDINAL_POSITION;

SELECT '=== STRUCTURE CHECK COMPLETE ===' AS STATUS;
