-- =====================================================================
-- DISCOVER CURRENT TABLE STRUCTURES
-- Purpose: Get complete structure of all tables to build correct implementation
-- =====================================================================

USE ROLE DEV_DEVELOPER;
USE WAREHOUSE DEV_WH;
USE DATABASE DEV_TRANSFORMATION;
USE SCHEMA SECURITY_ANALYTICS;

-- =====================================================================
-- SECTION 1: LIST ALL TABLES
-- =====================================================================

SELECT '=== ALL TABLES IN SCHEMA ===' AS SECTION;

SELECT
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    BYTES
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
ORDER BY TABLE_TYPE, TABLE_NAME;

-- =====================================================================
-- SECTION 2: DIMENSION TABLES - Get columns for each
-- =====================================================================

SELECT '=== DIMENSION TABLE STRUCTURES ===' AS SECTION;

-- DIM_DATES
SELECT 'DIM_DATES' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'DIM_DATES'
ORDER BY ORDINAL_POSITION;

-- DIM_HOST
SELECT 'DIM_HOST' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'DIM_HOST'
ORDER BY ORDINAL_POSITION;

-- DIM_ANCON_USERS
SELECT 'DIM_ANCON_USERS' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'DIM_ANCON_USERS'
ORDER BY ORDINAL_POSITION;

-- DIM_DEFENDER_ENDPOINTS
SELECT 'DIM_DEFENDER_ENDPOINTS' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'DIM_DEFENDER_ENDPOINTS'
ORDER BY ORDINAL_POSITION;

-- DIM_SNOW_DEVICES
SELECT 'DIM_SNOW_DEVICES' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'DIM_SNOW_DEVICES'
ORDER BY ORDINAL_POSITION;

-- DIM_CYBELANGEL_ALERTS
SELECT 'DIM_CYBELANGEL_ALERTS' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'DIM_CYBELANGEL_ALERTS'
ORDER BY ORDINAL_POSITION;

-- DIM_HARDWARE_INVENTORY
SELECT 'DIM_HARDWARE_INVENTORY' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'DIM_HARDWARE_INVENTORY'
ORDER BY ORDINAL_POSITION;

-- DIM_FIXED_VULNERABILITIES
SELECT 'DIM_FIXED_VULNERABILITIES' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'DIM_FIXED_VULNERABILITIES'
ORDER BY ORDINAL_POSITION;

-- DIM_FARRANS_ENDPOINTS
SELECT 'DIM_FARRANS_ENDPOINTS' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'DIM_FARRANS_ENDPOINTS'
ORDER BY ORDINAL_POSITION;

-- DIM_BITSIGHT_RISK_VECTORS
SELECT 'DIM_BITSIGHT_RISK_VECTORS' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'DIM_BITSIGHT_RISK_VECTORS'
ORDER BY ORDINAL_POSITION;

-- DIM_AV_OPCO
SELECT 'DIM_AV_OPCO' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'DIM_AV_OPCO'
ORDER BY ORDINAL_POSITION;

-- DIM_OPCO
SELECT 'DIM_OPCO' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'DIM_OPCO'
ORDER BY ORDINAL_POSITION;

-- DIM_USER
SELECT 'DIM_USER' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'DIM_USER'
ORDER BY ORDINAL_POSITION;

-- =====================================================================
-- SECTION 3: FACT TABLES - Get columns for each
-- =====================================================================

SELECT '=== FACT TABLE STRUCTURES ===' AS SECTION;

-- FACT_REMEDIATION_EVENTS
SELECT 'FACT_REMEDIATION_EVENTS' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'FACT_REMEDIATION_EVENTS'
ORDER BY ORDINAL_POSITION;

-- FACT_SENTINEL_ENDPOINTS
SELECT 'FACT_SENTINEL_ENDPOINTS' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'FACT_SENTINEL_ENDPOINTS'
ORDER BY ORDINAL_POSITION;

-- FACT_DEFENDER_THREATS
SELECT 'FACT_DEFENDER_THREATS' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'FACT_DEFENDER_THREATS'
ORDER BY ORDINAL_POSITION;

-- FACT_CYBELANGEL_THREATS
SELECT 'FACT_CYBELANGEL_THREATS' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'FACT_CYBELANGEL_THREATS'
ORDER BY ORDINAL_POSITION;

-- FACT_QUALYS_HOST_SCANS
SELECT 'FACT_QUALYS_HOST_SCANS' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'FACT_QUALYS_HOST_SCANS'
ORDER BY ORDINAL_POSITION;

-- FACT_AV_HEALTH
SELECT 'FACT_AV_HEALTH' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'FACT_AV_HEALTH'
ORDER BY ORDINAL_POSITION;

-- FACT_BITSIGHT_FINDINGS
SELECT 'FACT_BITSIGHT_FINDINGS' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'FACT_BITSIGHT_FINDINGS'
ORDER BY ORDINAL_POSITION;

-- FACT_FARRANS_HEALTH
SELECT 'FACT_FARRANS_HEALTH' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'FACT_FARRANS_HEALTH'
ORDER BY ORDINAL_POSITION;

-- FACT_EDR (from our base tables)
SELECT 'FACT_EDR' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'FACT_EDR'
ORDER BY ORDINAL_POSITION;

-- FACT_QUALYS (from our base tables)
SELECT 'FACT_QUALYS' AS TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'FACT_QUALYS'
ORDER BY ORDINAL_POSITION;

-- =====================================================================
-- SECTION 4: EXISTING CONSTRAINTS
-- =====================================================================

SELECT '=== EXISTING PRIMARY KEYS ===' AS SECTION;

SELECT
    TABLE_NAME,
    CONSTRAINT_NAME,
    CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND CONSTRAINT_TYPE = 'PRIMARY KEY'
ORDER BY TABLE_NAME;

SELECT '=== EXISTING FOREIGN KEYS ===' AS SECTION;

SELECT
    TABLE_NAME,
    CONSTRAINT_NAME,
    CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND CONSTRAINT_TYPE = 'FOREIGN KEY'
ORDER BY TABLE_NAME;

SELECT '=== EXISTING UNIQUE CONSTRAINTS ===' AS SECTION;

SELECT
    TABLE_NAME,
    CONSTRAINT_NAME,
    CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND CONSTRAINT_TYPE = 'UNIQUE'
ORDER BY TABLE_NAME;

-- =====================================================================
-- SECTION 5: CHECK IMPLEMENTATION_LOG STRUCTURE
-- =====================================================================

SELECT '=== IMPLEMENTATION_LOG STRUCTURE ===' AS SECTION;

SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ITSECKPI_BACKUP' AND TABLE_NAME = 'IMPLEMENTATION_LOG'
ORDER BY ORDINAL_POSITION;

SELECT '=== DISCOVERY COMPLETE ===' AS SECTION;
