-- =====================================================================
-- EXTRACT COMPLETE ERD METADATA - All objects for comprehensive ERDs
-- =====================================================================

USE ROLE DEV_DEVELOPER;
USE WAREHOUSE DEV_WH;

-- =====================================================================
-- SUMMARY: Object counts across all layers
-- =====================================================================

SELECT '=== ARCHITECTURE SUMMARY ===' AS SECTION;

SELECT
    'DEV_LANDING' as DATABASE_NAME,
    (SELECT COUNT(*) FROM DEV_LANDING.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_TYPE = 'BASE TABLE') as TABLES,
    (SELECT COUNT(*) FROM DEV_LANDING.INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS') as VIEWS,
    0 as PROCEDURES,
    0 as TASKS
UNION ALL
SELECT
    'DEV_TRANSFORMATION' as DATABASE_NAME,
    (SELECT COUNT(*) FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_TYPE = 'BASE TABLE') as TABLES,
    (SELECT COUNT(*) FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS') as VIEWS,
    (SELECT COUNT(*) FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.PROCEDURES WHERE PROCEDURE_SCHEMA = 'SECURITY_ANALYTICS') as PROCEDURES,
    (SELECT COUNT(*) FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TASKS WHERE TASK_SCHEMA = 'SECURITY_ANALYTICS') as TASKS
UNION ALL
SELECT
    'DEV_REPORTING' as DATABASE_NAME,
    (SELECT COUNT(*) FROM DEV_REPORTING.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_TYPE = 'BASE TABLE') as TABLES,
    (SELECT COUNT(*) FROM DEV_REPORTING.INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS') as VIEWS,
    (SELECT COUNT(*) FROM DEV_REPORTING.INFORMATION_SCHEMA.PROCEDURES WHERE PROCEDURE_SCHEMA = 'SECURITY_ANALYTICS') as PROCEDURES,
    0 as TASKS;

-- =====================================================================
-- LAYER 1: DEV_LANDING - Complete Inventory
-- =====================================================================

SELECT '=== LAYER 1: DEV_LANDING - TABLES ===' AS SECTION;

USE DATABASE DEV_LANDING;
USE SCHEMA SECURITY_ANALYTICS;

SELECT
    'LANDING' as LAYER,
    'TABLE' as OBJECT_TYPE,
    TABLE_NAME as OBJECT_NAME,
    ROW_COUNT,
    ROUND(BYTES/1024/1024, 2) as SIZE_MB,
    COMMENT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;

SELECT '=== LAYER 1: DEV_LANDING - VIEWS ===' AS SECTION;

SELECT
    'LANDING' as LAYER,
    'VIEW' as OBJECT_TYPE,
    TABLE_NAME as OBJECT_NAME,
    COMMENT
FROM INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
ORDER BY TABLE_NAME;

-- =====================================================================
-- LAYER 2: DEV_TRANSFORMATION - Complete Inventory
-- =====================================================================

SELECT '=== LAYER 2: DEV_TRANSFORMATION - DIMENSION TABLES ===' AS SECTION;

USE DATABASE DEV_TRANSFORMATION;
USE SCHEMA SECURITY_ANALYTICS;

SELECT
    'TRANSFORMATION' as LAYER,
    'DIMENSION' as OBJECT_TYPE,
    TABLE_NAME as OBJECT_NAME,
    ROW_COUNT,
    ROUND(BYTES/1024/1024, 2) as SIZE_MB,
    COMMENT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND TABLE_TYPE = 'BASE TABLE'
  AND TABLE_NAME LIKE 'DIM_%'
ORDER BY TABLE_NAME;

SELECT '=== LAYER 2: DEV_TRANSFORMATION - FACT TABLES ===' AS SECTION;

SELECT
    'TRANSFORMATION' as LAYER,
    'FACT' as OBJECT_TYPE,
    TABLE_NAME as OBJECT_NAME,
    ROW_COUNT,
    ROUND(BYTES/1024/1024, 2) as SIZE_MB,
    COMMENT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND TABLE_TYPE = 'BASE TABLE'
  AND TABLE_NAME LIKE 'FACT_%'
ORDER BY TABLE_NAME;

SELECT '=== LAYER 2: DEV_TRANSFORMATION - OTHER TABLES ===' AS SECTION;

SELECT
    'TRANSFORMATION' as LAYER,
    'TABLE' as OBJECT_TYPE,
    TABLE_NAME as OBJECT_NAME,
    ROW_COUNT,
    ROUND(BYTES/1024/1024, 2) as SIZE_MB,
    COMMENT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND TABLE_TYPE = 'BASE TABLE'
  AND TABLE_NAME NOT LIKE 'DIM_%'
  AND TABLE_NAME NOT LIKE 'FACT_%'
ORDER BY TABLE_NAME;

SELECT '=== LAYER 2: DEV_TRANSFORMATION - VIEWS ===' AS SECTION;

SELECT
    'TRANSFORMATION' as LAYER,
    'VIEW' as OBJECT_TYPE,
    TABLE_NAME as OBJECT_NAME,
    COMMENT
FROM INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
ORDER BY TABLE_NAME
LIMIT 50;

SELECT '=== LAYER 2: DEV_TRANSFORMATION - STORED PROCEDURES ===' AS SECTION;

SELECT
    'TRANSFORMATION' as LAYER,
    'PROCEDURE' as OBJECT_TYPE,
    PROCEDURE_NAME as OBJECT_NAME,
    ARGUMENT_SIGNATURE,
    PROCEDURE_LANGUAGE
FROM INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = 'SECURITY_ANALYTICS'
ORDER BY PROCEDURE_NAME;

SELECT '=== LAYER 2: DEV_TRANSFORMATION - TASKS ===' AS SECTION;

SELECT
    'TRANSFORMATION' as LAYER,
    'TASK' as OBJECT_TYPE,
    TASK_NAME as OBJECT_NAME,
    SCHEDULE,
    STATE,
    WAREHOUSE
FROM INFORMATION_SCHEMA.TASKS
WHERE TASK_SCHEMA = 'SECURITY_ANALYTICS'
ORDER BY TASK_NAME;

-- =====================================================================
-- LAYER 3: DEV_REPORTING - Complete Inventory
-- =====================================================================

SELECT '=== LAYER 3: DEV_REPORTING - TABLES ===' AS SECTION;

USE DATABASE DEV_REPORTING;
USE SCHEMA SECURITY_ANALYTICS;

SELECT
    'REPORTING' as LAYER,
    'TABLE' as OBJECT_TYPE,
    TABLE_NAME as OBJECT_NAME,
    ROW_COUNT,
    ROUND(BYTES/1024/1024, 2) as SIZE_MB,
    COMMENT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;

SELECT '=== LAYER 3: DEV_REPORTING - VIEWS (Part 1) ===' AS SECTION;

SELECT
    'REPORTING' as LAYER,
    'VIEW' as OBJECT_TYPE,
    TABLE_NAME as OBJECT_NAME,
    COMMENT
FROM INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
ORDER BY TABLE_NAME
LIMIT 50;

SELECT '=== LAYER 3: DEV_REPORTING - VIEWS (Part 2) ===' AS SECTION;

SELECT
    'REPORTING' as LAYER,
    'VIEW' as OBJECT_TYPE,
    TABLE_NAME as OBJECT_NAME,
    COMMENT
FROM INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
ORDER BY TABLE_NAME
LIMIT 50 OFFSET 50;

SELECT '=== LAYER 3: DEV_REPORTING - VIEWS (Part 3) ===' AS SECTION;

SELECT
    'REPORTING' as LAYER,
    'VIEW' as OBJECT_TYPE,
    TABLE_NAME as OBJECT_NAME,
    COMMENT
FROM INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
ORDER BY TABLE_NAME
LIMIT 50 OFFSET 100;

SELECT '=== LAYER 3: DEV_REPORTING - STORED PROCEDURES ===' AS SECTION;

SELECT
    'REPORTING' as LAYER,
    'PROCEDURE' as OBJECT_TYPE,
    PROCEDURE_NAME as OBJECT_NAME,
    ARGUMENT_SIGNATURE,
    PROCEDURE_LANGUAGE
FROM INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = 'SECURITY_ANALYTICS'
ORDER BY PROCEDURE_NAME;

-- =====================================================================
-- KEY DIMENSION TABLES - Detailed structure
-- =====================================================================

SELECT '=== KEY DIMENSIONS - DIM_OPCO ===' AS SECTION;

USE DATABASE DEV_TRANSFORMATION;
USE SCHEMA SECURITY_ANALYTICS;

SELECT 'DIM_OPCO' as TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'DIM_OPCO'
ORDER BY ORDINAL_POSITION;

SELECT '=== KEY DIMENSIONS - DIM_HOST ===' AS SECTION;

SELECT 'DIM_HOST' as TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'DIM_HOST'
ORDER BY ORDINAL_POSITION;

SELECT '=== KEY DIMENSIONS - DIM_DATES ===' AS SECTION;

SELECT 'DIM_DATES' as TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'DIM_DATES'
ORDER BY ORDINAL_POSITION;

SELECT '=== KEY DIMENSIONS - DIM_USER ===' AS SECTION;

SELECT 'DIM_USER' as TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'DIM_USER'
ORDER BY ORDINAL_POSITION;

-- =====================================================================
-- KEY FACT TABLES - Detailed structure
-- =====================================================================

SELECT '=== KEY FACTS - FACT_EDR ===' AS SECTION;

SELECT 'FACT_EDR' as TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'FACT_EDR'
ORDER BY ORDINAL_POSITION;

SELECT '=== KEY FACTS - FACT_QUALYS ===' AS SECTION;

SELECT 'FACT_QUALYS' as TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'FACT_QUALYS'
ORDER BY ORDINAL_POSITION;

-- =====================================================================
-- ALL RELATIONSHIPS (PKs & FKs)
-- =====================================================================

SELECT '=== ALL PRIMARY KEYS ===' AS SECTION;

SELECT
    TABLE_NAME,
    CONSTRAINT_NAME as PK_NAME
FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND CONSTRAINT_TYPE = 'PRIMARY KEY'
ORDER BY TABLE_NAME;

SELECT '=== ALL FOREIGN KEYS ===' AS SECTION;

SELECT
    TABLE_NAME,
    CONSTRAINT_NAME as FK_NAME
FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND CONSTRAINT_TYPE = 'FOREIGN KEY'
ORDER BY TABLE_NAME;

SELECT '=== COMPLETE METADATA EXTRACTION DONE ===' AS STATUS;
