-- Fix the last 2 missing views

USE ROLE DEV_DEVELOPER;
USE WAREHOUSE DEV_WH;
USE DATABASE DEV_TRANSFORMATION;
USE SCHEMA SECURITY_ANALYTICS;

CREATE OR REPLACE VIEW VW_ETL_ERRORS AS
SELECT
    LOG_ID,
    PIPELINE_NAME,
    SOURCE_TABLE,
    TARGET_TABLE,
    ERROR_MESSAGE,
    CREATED_AT as ERROR_TIME
FROM ETL_PIPELINE_LOG
WHERE STATUS = 'FAILED'
  AND CREATED_AT >= DATEADD('day', -7, CURRENT_DATE())
ORDER BY CREATED_AT DESC;

SELECT 'VW_ETL_ERRORS created' AS RESULT;

CREATE OR REPLACE VIEW VW_EXECUTIVE_KPI_DASHBOARD AS
SELECT
    d.DATE,
    d.YEAR,
    d.QUARTER,
    d.MONTH_NAME,
    o.OPCO_NAME,
    o.REGION,
    o.DIVISION,
    COUNT(DISTINCT h.HOST_KEY) as TOTAL_HOSTS,
    COUNT(DISTINCT CASE WHEN e.THREAT_COUNT > 0 THEN e.EDR_KEY END) as HOSTS_WITH_THREATS,
    SUM(e.THREAT_COUNT) as TOTAL_THREATS,
    ROUND(COUNT(DISTINCT CASE WHEN e.THREAT_COUNT > 0 THEN e.EDR_KEY END) * 100.0 /
          NULLIF(COUNT(DISTINCT h.HOST_KEY), 0), 2) as THREAT_PERCENTAGE
FROM DEV_TRANSFORMATION.SECURITY_ANALYTICS.DIM_DATES d
CROSS JOIN DEV_TRANSFORMATION.SECURITY_ANALYTICS.DIM_OPCO o
LEFT JOIN DEV_TRANSFORMATION.SECURITY_ANALYTICS.DIM_HOST h
    ON h.OPCO_ID = o.OPCO_ID
LEFT JOIN DEV_TRANSFORMATION.SECURITY_ANALYTICS.FACT_EDR e
    ON e.HOST_ID = h.HOST_KEY::TEXT
WHERE d.DATE >= DATEADD('month', -12, CURRENT_DATE())
  AND d.DATE <= CURRENT_DATE()
GROUP BY d.DATE, d.YEAR, d.QUARTER, d.MONTH_NAME, o.OPCO_NAME, o.REGION, o.DIVISION;

SELECT 'VW_EXECUTIVE_KPI_DASHBOARD created' AS RESULT;

SELECT 'VW_ETL_ERRORS' as VIEW_NAME, COUNT(*) as ROW_COUNT FROM VW_ETL_ERRORS;

SELECT 'VW_EXECUTIVE_KPI_DASHBOARD' as VIEW_NAME, COUNT(*) as ROW_COUNT FROM VW_EXECUTIVE_KPI_DASHBOARD;

SELECT '=== ALL VIEWS COMPLETE ===' AS STATUS;
