-- =====================================================================
-- EXTRACT ERD METADATA - Complete relationship mapping for all 3 layers
-- =====================================================================

USE ROLE DEV_DEVELOPER;
USE WAREHOUSE DEV_WH;

-- =====================================================================
-- LAYER 1: DEV_LANDING (Landing Zone)
-- =====================================================================

SELECT '=== LAYER 1: DEV_LANDING ===' AS SECTION;

-- Landing tables
USE DATABASE DEV_LANDING;
USE SCHEMA SECURITY_ANALYTICS;

SELECT
    'LANDING' as LAYER,
    TABLE_NAME,
    ROW_COUNT,
    BYTES
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;

-- Landing table structures
SELECT
    'LANDING' as LAYER,
    TABLE_NAME,
    COLUMN_NAME,
    ORDINAL_POSITION,
    DATA_TYPE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- =====================================================================
-- LAYER 2: DEV_TRANSFORMATION (Business Logic / Star Schema)
-- =====================================================================

SELECT '=== LAYER 2: DEV_TRANSFORMATION ===' AS SECTION;

USE DATABASE DEV_TRANSFORMATION;
USE SCHEMA SECURITY_ANALYTICS;

-- All tables in transformation
SELECT
    'TRANSFORMATION' as LAYER,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    BYTES,
    CASE
        WHEN TABLE_NAME LIKE 'DIM_%' THEN 'DIMENSION'
        WHEN TABLE_NAME LIKE 'FACT_%' THEN 'FACT'
        WHEN TABLE_NAME LIKE 'STG_%' THEN 'STAGING'
        ELSE 'OTHER'
    END as TABLE_CATEGORY
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_CATEGORY, TABLE_NAME;

-- All columns in transformation
SELECT
    'TRANSFORMATION' as LAYER,
    TABLE_NAME,
    COLUMN_NAME,
    ORDINAL_POSITION,
    DATA_TYPE,
    IS_NULLABLE,
    CASE
        WHEN TABLE_NAME LIKE 'DIM_%' THEN 'DIMENSION'
        WHEN TABLE_NAME LIKE 'FACT_%' THEN 'FACT'
        ELSE 'OTHER'
    END as TABLE_CATEGORY
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND TABLE_NAME IN (
      SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
      WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_TYPE = 'BASE TABLE'
  )
ORDER BY TABLE_CATEGORY, TABLE_NAME, ORDINAL_POSITION;

-- Primary Keys in transformation
SELECT
    'TRANSFORMATION' as LAYER,
    tc.TABLE_NAME,
    tc.CONSTRAINT_NAME,
    'PRIMARY KEY' as CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
WHERE tc.TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
ORDER BY tc.TABLE_NAME;

-- Foreign Keys in transformation
SELECT
    'TRANSFORMATION' as LAYER,
    tc.TABLE_NAME,
    tc.CONSTRAINT_NAME,
    'FOREIGN KEY' as CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
WHERE tc.TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND tc.CONSTRAINT_TYPE = 'FOREIGN KEY'
ORDER BY tc.TABLE_NAME;

-- =====================================================================
-- LAYER 3: DEV_REPORTING (Analytics / Aggregated)
-- =====================================================================

SELECT '=== LAYER 3: DEV_REPORTING ===' AS SECTION;

USE DATABASE DEV_REPORTING;
USE SCHEMA SECURITY_ANALYTICS;

-- Reporting tables
SELECT
    'REPORTING' as LAYER,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    BYTES
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;

-- Reporting table structures
SELECT
    'REPORTING' as LAYER,
    TABLE_NAME,
    COLUMN_NAME,
    ORDINAL_POSITION,
    DATA_TYPE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND TABLE_NAME IN (
      SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
      WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_TYPE = 'BASE TABLE'
  )
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- Reporting views (for reference)
SELECT
    'REPORTING' as LAYER,
    TABLE_NAME as VIEW_NAME,
    'VIEW' as OBJECT_TYPE
FROM INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
ORDER BY TABLE_NAME;

-- =====================================================================
-- CROSS-LAYER RELATIONSHIPS (Data Lineage)
-- =====================================================================

SELECT '=== CROSS-LAYER LINEAGE ===' AS SECTION;

USE DATABASE DEV_TRANSFORMATION;
USE SCHEMA SECURITY_ANALYTICS;

SELECT
    SOURCE_DATABASE,
    SOURCE_SCHEMA,
    SOURCE_TABLE,
    TARGET_DATABASE,
    TARGET_SCHEMA,
    TARGET_TABLE,
    TRANSFORMATION_LOGIC,
    UPDATE_FREQUENCY
FROM DATA_LINEAGE_CATALOG
ORDER BY SOURCE_DATABASE, TARGET_DATABASE, SOURCE_TABLE;

SELECT '=== ERD METADATA EXTRACTION COMPLETE ===' AS STATUS;
