-- Quick SQL to recreate Splunk app for manual deployment
-- Run this in Snowflake SQL worksheet

-- 1. Drop existing app if it exists
DROP STREAMLIT IF EXISTS DEV_REPORTING.SECURITY_ANALYTICS.SPLUNK_APP;

-- 2. Create new app with inline code capability
CREATE STREAMLIT DEV_REPORTING.SECURITY_ANALYTICS.SPLUNK_APP
  QUERY_WAREHOUSE = 'DEV_WH'
  COMMENT = 'SECURITY_ANALYTICS Splunk - Manual Deployment';

-- After running this:
-- 1. Go to the app in UI
-- 2. Click Edit
-- 3. Paste the content from 08_STREAMLIT_APPS_FIXED/Splunk/streamlit_app.py
-- 4. Save and Run

-- Repeat for other apps:
DROP STREAMLIT IF EXISTS DEV_REPORTING.SECURITY_ANALYTICS.CROWDSTRIKE_APP;
CREATE STREAMLIT DEV_REPORTING.SECURITY_ANALYTICS.CROWDSTRIKE_APP
  QUERY_WAREHOUSE = 'DEV_WH'
  COMMENT = 'SECURITY_ANALYTICS Crowdstrike - Manual Deployment';

DROP STREAMLIT IF EXISTS DEV_REPORTING.SECURITY_ANALYTICS.SERVICENOW_APP;
CREATE STREAMLIT DEV_REPORTING.SECURITY_ANALYTICS.SERVICENOW_APP
  QUERY_WAREHOUSE = 'DEV_WH'
  COMMENT = 'SECURITY_ANALYTICS ServiceNow - Manual Deployment';

DROP STREAMLIT IF EXISTS DEV_REPORTING.SECURITY_ANALYTICS.QUALYS_APP;
CREATE STREAMLIT DEV_REPORTING.SECURITY_ANALYTICS.QUALYS_APP
  QUERY_WAREHOUSE = 'DEV_WH'
  COMMENT = 'SECURITY_ANALYTICS Qualys - Manual Deployment';

DROP STREAMLIT IF EXISTS DEV_REPORTING.SECURITY_ANALYTICS.ZSCALER_APP;
CREATE STREAMLIT DEV_REPORTING.SECURITY_ANALYTICS.ZSCALER_APP
  QUERY_WAREHOUSE = 'DEV_WH'
  COMMENT = 'SECURITY_ANALYTICS Zscaler - Manual Deployment';

DROP STREAMLIT IF EXISTS DEV_REPORTING.SECURITY_ANALYTICS.SENTINELONE_APP;
CREATE STREAMLIT DEV_REPORTING.SECURITY_ANALYTICS.SENTINELONE_APP
  QUERY_WAREHOUSE = 'DEV_WH'
  COMMENT = 'SECURITY_ANALYTICS SentinelOne - Manual Deployment';