-- ============================================================================
-- CREATE MISSING BASE TABLES - ULTRA SIMPLE VERSION
-- ============================================================================
-- Purpose: Create only the minimum tables with sample data
-- NO dependencies on existing DIM_HOST structure
-- ============================================================================

USE ROLE DEV_DEVELOPER;
USE WAREHOUSE DEV_WH;

-- ============================================================================
-- SECTION 1: DIM_OPCO
-- ============================================================================

USE DATABASE DEV_TRANSFORMATION;
USE SCHEMA SECURITY_ANALYTICS;

SELECT '=== Step 1: Creating DIM_OPCO ===' AS STEP;

CREATE TABLE IF NOT EXISTS DIM_OPCO (
    OPCO_ID NUMBER PRIMARY KEY,
    OPCO_CODE VARCHAR(50),
    OPCO_NAME VARCHAR(100),
    REGION VARCHAR(50),
    DIVISION VARCHAR(100),
    COUNTRY VARCHAR(100),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Clear and insert fresh data
DELETE FROM DIM_OPCO;

INSERT INTO DIM_OPCO (OPCO_ID, OPCO_CODE, OPCO_NAME, REGION, DIVISION, COUNTRY)
VALUES
    (1, 'OPCO_001', 'North America OpCo', 'North America', 'IT Security', 'USA'),
    (2, 'OPCO_002', 'Europe OpCo', 'Europe', 'IT Security', 'UK'),
    (3, 'OPCO_003', 'APAC OpCo', 'Asia Pacific', 'IT Security', 'Australia');

SELECT 'DIM_OPCO: ' || COUNT(*) || ' rows' AS RESULT FROM DIM_OPCO;

-- ============================================================================
-- SECTION 2: FACT_EDR
-- ============================================================================

SELECT '=== Step 2: Creating FACT_EDR ===' AS STEP;

CREATE TABLE IF NOT EXISTS FACT_EDR (
    EDR_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    DATE_KEY NUMBER,
    HOST_ID VARCHAR(255),
    ENDPOINT_ID VARCHAR(255),
    EDR_PLATFORM VARCHAR(50),
    AGENT_VERSION VARCHAR(50),
    AGENT_STATUS VARCHAR(50),
    LAST_SEEN_DATE TIMESTAMP,
    THREAT_COUNT NUMBER DEFAULT 0,
    THREAT_NAME VARCHAR(500),
    THREAT_TYPE VARCHAR(100),
    THREAT_STATUS VARCHAR(50),
    DETECTION_TIME TIMESTAMP,
    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Insert 20 sample records
INSERT INTO FACT_EDR (DATE_KEY, HOST_ID, ENDPOINT_ID, EDR_PLATFORM, AGENT_STATUS, LAST_SEEN_DATE)
SELECT
    TO_NUMBER(TO_CHAR(CURRENT_DATE(), 'YYYYMMDD')),
    'HOST_' || LPAD(SEQ4(), 5, '0'),
    'ENDPOINT_' || LPAD(SEQ4(), 5, '0'),
    CASE WHEN SEQ4() % 3 = 0 THEN 'CrowdStrike'
         WHEN SEQ4() % 3 = 1 THEN 'SentinelOne'
         ELSE 'Microsoft Defender' END,
    CASE WHEN SEQ4() % 10 = 0 THEN 'Offline' ELSE 'Healthy' END,
    CURRENT_TIMESTAMP()
FROM TABLE(GENERATOR(ROWCOUNT => 20))
WHERE NOT EXISTS (SELECT 1 FROM FACT_EDR LIMIT 1);

SELECT 'FACT_EDR: ' || COUNT(*) || ' rows' AS RESULT FROM FACT_EDR;

-- ============================================================================
-- SECTION 3: FACT_QUALYS
-- ============================================================================

SELECT '=== Step 3: Creating FACT_QUALYS ===' AS STEP;

CREATE TABLE IF NOT EXISTS FACT_QUALYS (
    QUALYS_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    DATE_KEY NUMBER,
    HOST_ID VARCHAR(255),
    VULN_ID VARCHAR(255),
    CVE_ID VARCHAR(50),
    VULN_TITLE VARCHAR(500),
    SEVERITY VARCHAR(50),
    CVSS_SCORE FLOAT,
    CRITICAL_VULNS NUMBER DEFAULT 0,
    HIGH_VULNS NUMBER DEFAULT 0,
    MEDIUM_VULNS NUMBER DEFAULT 0,
    LOW_VULNS NUMBER DEFAULT 0,
    TOTAL_VULNERABILITIES NUMBER DEFAULT 0,
    OLDEST_CRITICAL_VULN_AGE_DAYS NUMBER,
    FIRST_DETECTED_DATE DATE,
    IS_EXPLOITED_IN_WILD BOOLEAN DEFAULT FALSE,
    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Insert 20 sample records
INSERT INTO FACT_QUALYS (DATE_KEY, HOST_ID, VULN_ID, SEVERITY, CVSS_SCORE, CRITICAL_VULNS, HIGH_VULNS, TOTAL_VULNERABILITIES, FIRST_DETECTED_DATE)
SELECT
    TO_NUMBER(TO_CHAR(CURRENT_DATE(), 'YYYYMMDD')),
    'HOST_' || LPAD(SEQ4(), 5, '0'),
    'CVE-2024-' || LPAD(UNIFORM(1000, 9999, RANDOM()), 4, '0'),
    CASE WHEN SEQ4() % 4 = 0 THEN 'CRITICAL'
         WHEN SEQ4() % 4 = 1 THEN 'HIGH'
         WHEN SEQ4() % 4 = 2 THEN 'MEDIUM'
         ELSE 'LOW' END,
    UNIFORM(3, 10, RANDOM()),
    CASE WHEN SEQ4() % 4 = 0 THEN 1 ELSE 0 END,
    CASE WHEN SEQ4() % 4 = 1 THEN 1 ELSE 0 END,
    1,
    DATEADD('day', -UNIFORM(1, 90, RANDOM()), CURRENT_DATE())
FROM TABLE(GENERATOR(ROWCOUNT => 20))
WHERE NOT EXISTS (SELECT 1 FROM FACT_QUALYS LIMIT 1);

SELECT 'FACT_QUALYS: ' || COUNT(*) || ' rows' AS RESULT FROM FACT_QUALYS;

-- ============================================================================
-- SECTION 4: FACT_PATCHES
-- ============================================================================

SELECT '=== Step 4: Creating FACT_PATCHES ===' AS STEP;

CREATE TABLE IF NOT EXISTS FACT_PATCHES (
    PATCH_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    DATE_KEY NUMBER,
    HOST_ID VARCHAR(255),
    OS_PATCH_LEVEL VARCHAR(100),
    MISSING_CRITICAL_PATCHES NUMBER DEFAULT 0,
    LAST_PATCH_DATE DATE,
    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

SELECT 'FACT_PATCHES: Created (empty for now)' AS RESULT;

-- ============================================================================
-- SECTION 5: FACT_INCIDENTS
-- ============================================================================

SELECT '=== Step 5: Creating FACT_INCIDENTS ===' AS STEP;

CREATE TABLE IF NOT EXISTS FACT_INCIDENTS (
    INCIDENT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    DATE_KEY NUMBER,
    HOST_ID VARCHAR(255),
    INCIDENT_ID VARCHAR(255),
    INCIDENT_TYPE VARCHAR(100),
    SEVERITY VARCHAR(50),
    STATUS VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    RESOLVED_DATE TIMESTAMP,
    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

SELECT 'FACT_INCIDENTS: Created (empty for now)' AS RESULT;

-- ============================================================================
-- SECTION 6: TBL_KPI_MASTER (Reporting)
-- ============================================================================

USE DATABASE DEV_REPORTING;
USE SCHEMA SECURITY_ANALYTICS;

SELECT '=== Step 6: Creating TBL_KPI_MASTER ===' AS STEP;

CREATE TABLE IF NOT EXISTS TBL_KPI_MASTER (
    KPI_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    DATE_KEY NUMBER,
    OPCO_ID NUMBER,
    HOST_ID VARCHAR(255),
    CYBER_MATURITY_SCORE FLOAT,
    TOTAL_POLICY_EXCEPTIONS NUMBER,
    OVERDUE_EXCEPTIONS NUMBER,
    VENDOR_RISK_SCORE FLOAT,
    HIGH_RISK_VENDORS NUMBER,
    ACCESS_REVIEWS_COMPLETED_PCT FLOAT,
    EDR_COVERAGE_ALL_PCT FLOAT,
    EDR_COVERAGE_SOX_PCT FLOAT,
    TOTAL_ASSETS NUMBER,
    EDR_PROTECTED_ASSETS NUMBER,
    UNPROTECTED_ASSETS NUMBER,
    EMAIL_DOMAIN_SECURITY_PCT FLOAT,
    DMARC_COMPLIANT_DOMAINS NUMBER,
    PHISHING_CLICK_RATE_PCT FLOAT,
    PHISHING_SIMULATIONS_SENT NUMBER,
    PHISHING_CLICKS NUMBER,
    MEAN_TIME_TO_ENGAGE_HOURS FLOAT,
    VULN_SCAN_COVERAGE_ALL_PCT FLOAT,
    VULN_SCAN_COVERAGE_SOX_PCT FLOAT,
    VULN_SCAN_COVERAGE_SERVERS_PCT FLOAT,
    VULN_SCAN_COVERAGE_WORKSTATIONS_PCT FLOAT,
    VULN_SCAN_COVERAGE_DATABASES_PCT FLOAT,
    VULN_SCAN_COVERAGE_NETWORK_PCT FLOAT,
    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Insert sample KPIs for each OpCo
INSERT INTO TBL_KPI_MASTER (
    DATE_KEY, OPCO_ID,
    EDR_COVERAGE_ALL_PCT, TOTAL_ASSETS, EDR_PROTECTED_ASSETS, UNPROTECTED_ASSETS,
    VULN_SCAN_COVERAGE_ALL_PCT, PHISHING_CLICK_RATE_PCT,
    EMAIL_DOMAIN_SECURITY_PCT, ACCESS_REVIEWS_COMPLETED_PCT,
    CYBER_MATURITY_SCORE, MEAN_TIME_TO_ENGAGE_HOURS
)
SELECT
    TO_NUMBER(TO_CHAR(CURRENT_DATE(), 'YYYYMMDD')),
    opco_id,
    85.0 + UNIFORM(0, 10, RANDOM()),  -- EDR Coverage 85-95%
    100,
    ROUND(100 * (85.0 + UNIFORM(0, 10, RANDOM())) / 100),
    ROUND(100 * (1 - (85.0 + UNIFORM(0, 10, RANDOM())) / 100)),
    75.0 + UNIFORM(0, 15, RANDOM()),  -- Vuln Coverage 75-90%
    2.0 + UNIFORM(0, 5, RANDOM()),    -- Phishing 2-7%
    88.0 + UNIFORM(0, 10, RANDOM()),  -- Email Security 88-98%
    80.0 + UNIFORM(0, 15, RANDOM()),  -- Access Reviews 80-95%
    3.0 + UNIFORM(0, 2, RANDOM()),    -- Maturity 3-5
    0.2 + UNIFORM(0, 1, RANDOM())     -- MTTE 0.2-1.2 hours
FROM (SELECT 1 AS opco_id UNION ALL SELECT 2 UNION ALL SELECT 3) opcos
WHERE NOT EXISTS (
    SELECT 1 FROM TBL_KPI_MASTER
    WHERE DATE_KEY = TO_NUMBER(TO_CHAR(CURRENT_DATE(), 'YYYYMMDD'))
);

SELECT 'TBL_KPI_MASTER: ' || COUNT(*) || ' rows' AS RESULT FROM TBL_KPI_MASTER;

-- ============================================================================
-- SECTION 7: TBL_DATA_QUALITY_SCORES (Placeholder)
-- ============================================================================

SELECT '=== Step 7: Creating TBL_DATA_QUALITY_SCORES ===' AS STEP;

CREATE TABLE IF NOT EXISTS TBL_DATA_QUALITY_SCORES (
    SCORE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    DATE_KEY NUMBER,
    OPCO_ID NUMBER,
    TABLE_NAME VARCHAR(255),
    LAYER VARCHAR(50),
    COMPLETENESS_SCORE FLOAT,
    ACCURACY_SCORE FLOAT,
    FRESHNESS_SCORE FLOAT,
    CONSISTENCY_SCORE FLOAT,
    VALIDITY_SCORE FLOAT,
    OVERALL_DQ_SCORE FLOAT,
    SCORE_GRADE VARCHAR(10),
    CONFIDENCE_LEVEL VARCHAR(20),
    CALCULATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    CALCULATED_DATE DATE DEFAULT CURRENT_DATE()
);

SELECT 'TBL_DATA_QUALITY_SCORES: Created (will be populated by Enhancement 2)' AS RESULT;

-- ============================================================================
-- FINAL VERIFICATION
-- ============================================================================

SELECT '========================================' AS STEP;
SELECT '=== ALL TABLES CREATED SUCCESSFULLY ===' AS STEP;
SELECT '========================================' AS STEP;

USE DATABASE DEV_TRANSFORMATION;
SELECT 'DEV_TRANSFORMATION' AS LOCATION, TABLE_NAME, ROW_COUNT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND TABLE_NAME IN ('DIM_OPCO', 'FACT_EDR', 'FACT_QUALYS', 'FACT_PATCHES', 'FACT_INCIDENTS')
ORDER BY TABLE_NAME;

USE DATABASE DEV_REPORTING;
SELECT 'DEV_REPORTING' AS LOCATION, TABLE_NAME, ROW_COUNT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND TABLE_NAME IN ('TBL_KPI_MASTER', 'TBL_DATA_QUALITY_SCORES')
ORDER BY TABLE_NAME;

SELECT '========================================' AS STEP;
SELECT 'NEXT STEP: Run the 4 enhancements!' AS STEP;
SELECT '1. 01_PowerBI_Integration_Layer.sql' AS STEP;
SELECT '2. 02_Data_Quality_Framework.sql' AS STEP;
SELECT '3. 03_Unified_User_Dimension.sql' AS STEP;
SELECT '4. 04_Near_RealTime_Capabilities.sql' AS STEP;
SELECT '========================================' AS STEP;
