-- ============================================================================
-- PREREQUISITES CHECK - Run this FIRST
-- ============================================================================
-- Purpose: Check if base tables exist before running enhancements
-- Author: Data Engineering Team
-- Date: 2025-10-07
-- ============================================================================

-- Set your role
USE ROLE DEV_DEVELOPER;
USE WAREHOUSE DEV_WH;

SELECT '=== CHECKING DATABASES ===' AS STEP;
SHOW DATABASES LIKE 'DEV%';

SELECT '=== CHECKING SCHEMAS ===' AS STEP;
SHOW SCHEMAS IN DATABASE DEV_TRANSFORMATION;
SHOW SCHEMAS IN DATABASE DEV_REPORTING;
SHOW SCHEMAS IN DATABASE DEV_LANDING;

SELECT '=== CHECKING TABLES IN DEV_TRANSFORMATION.SECURITY_ANALYTICS ===' AS STEP;
USE DATABASE DEV_TRANSFORMATION;
USE SCHEMA SECURITY_ANALYTICS;
SHOW TABLES;

SELECT '=== CHECKING TABLES IN DEV_REPORTING.SECURITY_ANALYTICS ===' AS STEP;
USE DATABASE DEV_REPORTING;
USE SCHEMA SECURITY_ANALYTICS;
SHOW TABLES;

SELECT '=== CHECKING CRITICAL TABLES ===' AS STEP;
-- Check if critical dimension tables exist
SELECT 'DIM_OPCO' AS TABLE_NAME,
       CASE WHEN COUNT(*) > 0 THEN '✓ EXISTS' ELSE '✗ MISSING' END AS STATUS
FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'DIM_OPCO'
UNION ALL
SELECT 'DIM_DATES',
       CASE WHEN COUNT(*) > 0 THEN '✓ EXISTS' ELSE '✗ MISSING' END
FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'DIM_DATES'
UNION ALL
SELECT 'DIM_HOST',
       CASE WHEN COUNT(*) > 0 THEN '✓ EXISTS' ELSE '✗ MISSING' END
FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'DIM_HOST'
UNION ALL
SELECT 'FACT_EDR',
       CASE WHEN COUNT(*) > 0 THEN '✓ EXISTS' ELSE '✗ MISSING' END
FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'FACT_EDR'
UNION ALL
SELECT 'FACT_QUALYS',
       CASE WHEN COUNT(*) > 0 THEN '✓ EXISTS' ELSE '✗ MISSING' END
FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'FACT_QUALYS'
UNION ALL
SELECT 'TBL_KPI_MASTER',
       CASE WHEN COUNT(*) > 0 THEN '✓ EXISTS' ELSE '✗ MISSING' END
FROM DEV_REPORTING.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS' AND TABLE_NAME = 'TBL_KPI_MASTER';

-- ============================================================================
-- RESULT INTERPRETATION:
-- ============================================================================
-- If you see "✗ MISSING" for any table:
--   → You need to run: 02_SQL_SCRIPTS\01_core_implementation\ITSECKPI_MODEL_IMPLEMENTATION_MASTER.sql FIRST
--
-- If you see "✓ EXISTS" for all tables:
--   → You can proceed with the 4 enhancements
-- ============================================================================
