// DBML Schema - LANDING Layer
// Database: DEV_LANDING
// Generated: 2025-10-06T10:42:59.755039

Table AD_COMPUTERS_ALUNGRIFFITHS {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_AMAT {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_ANCON {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_APG {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_ASHGROVE {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_BELGIUM {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_CRHPP_NET {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_CRH_CORP {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_CRH_NET {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_CRH_UNI_COM {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_DD_MM_YYYY {
  Note: 'List of computers with European-format dates, containing over 12,000 records. Data Category: Active Directory Table.(AD DD-MM-YYYY).'
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
  SOURCE_NAME TEXT
}

Table AD_COMPUTERS_DENMARK {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_DEV_CRH_UNI_NET {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_EMAT {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_EMAT_CRHPP_NET {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_EMAT_HCL {
  Note: 'Computers EMAT HCL, containing over 34,000 records. Data Category: Active Directory Table.'
  DOMAIN_NAME TEXT
  OU TEXT
  NAME TEXT
  SAMACCOUNTNAME TEXT
  OPERATINGSYSTEM TEXT
  IPV4ADDRESS TEXT
  DNSHOSTNAME TEXT
  DESCRIPTION TEXT
  DISTINGUISHEDNAME TEXT
  ENABLED TEXT
  WHENCREATED TEXT
  WHENCHANGED TEXT
  PWDLASTSET TEXT
  LASTLOGONDATE TEXT
  SOURCE_NAME TEXT
}

Table AD_COMPUTERS_EU_CRH_CORP_NET {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_FERROBETON_COMPUTE {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_FERROBETON_SERVERS {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_LEVIAT {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_MM_DD_YYYY {
  Note: 'List of computers with American-format dates, containing over 44,000 records. Data Category: Active Directory Table. (AMP MM-DD-YYYY).'
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
  SOURCE_NAME TEXT
}

Table AD_COMPUTERS_NETHERLANDS {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_NORTHSTONE {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_PHILIPINES {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_POLISH_COMPUTERS {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_POLISH_SERVERS {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_SLOVAKIA {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_TARMAC {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_UBAB {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}

Table AD_COMPUTERS_UKRAINE {
  NAME TEXT
  OPERATING_SYSTEM TEXT
  LAST_LOGON_DATE TEXT
  DISTINGUISHED_NAME TEXT
}
