// DBML Schema - REPORTING Layer
// Database: DEV_REPORTING
// Generated: 2025-10-06T10:42:59.756001

Table BOL_CROWDSTRIKE {
  HOSTNAME TEXT
  LAST_SEEN TEXT
  FIRST_SEEN TEXT
  PLATFORM TEXT
  OS_VERSION TEXT
  OS_BUILD TEXT
  OS_PRODUCT_NAME TEXT
  KERNEL_VERSION TEXT
  MODEL TEXT
  MANUFACTURER TEXT
  TYPE TEXT
  CHASSIS TEXT
  LAST_REBOOT TEXT
  OU TEXT
  SITE TEXT
  PREVENTION_POLICY TEXT
  RESPONSE_POLICY TEXT
  SENSOR_UPDATE_POLICY TEXT
  USB_DEVICE_POLICY TEXT
  KUBERNETES_ADMISSION_CONTROL_POLICY TEXT
  HOST_ID TEXT
  LOCAL_IP TEXT
  CONNECTION_IP TEXT
  DEFAULT_GATEWAY_IP TEXT
  EXTERNAL_IP TEXT
  DOMAIN TEXT
  MAC_ADDRESS TEXT
  CONNECTION_MAC_ADDRESS TEXT
  STATUS TEXT
  CPUID TEXT
  SERIAL_NUMBER TEXT
  SENSOR_VERSION TEXT
  SENSOR_TAGS TEXT
  CLOUD_SERVICE_PROVIDER TEXT
  CLOUD_SERVICE_ACCOUNT_ID TEXT
  CLOUD_SERVICE_INSTANCE_ID TEXT
  CLOUD_SERVICE_ZONE_GROUP TEXT
  KUBERNETES_CLUSTER_ID TEXT
  KUBERNETES_SERVER_GIT_VERSION TEXT
  KUBERNETES_SERVER_VERSION TEXT
  RFM TEXT
  LINUX_SENSOR_MODE TEXT
  DEPLOYMENT_TYPE TEXT
  EMAIL TEXT
  POD_ID TEXT
  POD_NAME TEXT
  POD_NAMESPACE TEXT
  POD_LABELS TEXT
  POD_ANNOTATIONS TEXT
  POD_IP4 TEXT
  POD_IP6 TEXT
  POD_HOSTNAME TEXT
  POD_HOST_IP4 TEXT
  POD_HOST_IP6 TEXT
  POD_SERVICE_ACCOUNT_NAME TEXT
  HOST_GROUPS TEXT
  LAST_LOGGED_IN_USER_ACCOUNT TEXT
  LAST_USER_ACCOUNT_LOGIN TEXT
}

Table FIXEDVULNERABILITIES {
  ASSET_ID NUMBER
  ID NUMBER
  IP TEXT
  TRACKING_METHOD TEXT
  NETWORK_ID NUMBER
  OS TEXT
  NETBIOS TEXT
  LAST_SCAN_DATETIME TIMESTAMP_NTZ
  LAST_VM_SCANNED_DATE TIMESTAMP_NTZ
  LAST_VM_SCANNED_DURATION NUMBER
  UNIQUE_VULN_ID TEXT
  QID TEXT
  TYPE TEXT
  SEVERITY TEXT
  SSL TEXT
  RESULTS TEXT
  STATUS TEXT
  FIRST_FOUND_DATETIME TEXT
  LAST_FOUND_DATETIME TEXT
  TIMES_FOUND TEXT
  LAST_TEST_DATETIME TEXT
  LAST_UPDATE_DATETIME TEXT
  LAST_FIXED_DATETIME TEXT
  FIRST_REOPENED_DATETIME TEXT
  LAST_REOPENED_DATETIME TEXT
  TIMES_REOPENED TEXT
  IS_IGNORED TEXT
  IS_DISABLED TEXT
  LAST_PROCESSED_DATETIME TEXT
}

Table HOSTS {
  AGENT_STATUS TEXT
  ASSET_ID NUMBER
  CLOUD_AGENT_RUNNING_ON TEXT
  CLOUD_PROVIDER TEXT
  CLOUD_RESOURCE_ID TEXT
  CLOUD_SERVICE TEXT
  COMMENTS TEXT
  DNS TEXT
  DNS_DATA_DOMAIN TEXT
  DNS_DATA_FQDN TEXT
  DNS_DATA_HOSTNAME TEXT
  EC2_INSTANCE_ID TEXT
  FIRST_FOUND_DATE TIMESTAMP_NTZ
  HARDWARE_UUID TEXT
  ID NUMBER
  IP TEXT
  LAST_ACTIVITY TIMESTAMP_NTZ
  LAST_BOOT TIMESTAMP_NTZ
  LAST_VM_AUTH_SCANNED_DATE TIMESTAMP_NTZ
  LAST_VM_AUTH_SCANNED_DURATION NUMBER
  LAST_VM_SCANNED_DATE TIMESTAMP_NTZ
  LAST_VM_SCANNED_DURATION NUMBER
  LAST_VULN_SCAN_DATETIME TIMESTAMP_NTZ
  NETBIOS TEXT
  NETWORK_ID NUMBER
  OS TEXT
  OWNER TEXT
  QG_HOSTID TEXT
  SERIAL_NUMBER TEXT
  TAGS_NAME TEXT
  TAGS_ID TEXT
  TRACKING_METHOD TEXT
  VALUE_1 TEXT
  VALUE_1_UD_ATTR TEXT
  VALUE_2 TEXT
  VALUE_2_UD_ATTR TEXT
  VALUE_3 TEXT
  VALUE_3_UD_ATTR TEXT
}

Table KB {
  BUGTRAQ_LIST VARIANT
  CATEGORY TEXT
  COMPLIANCE_LIST VARIANT
  CONSEQUENCE TEXT
  CORRELATION VARIANT
  CVE_LIST VARIANT
  CVSS VARIANT
  CVSS_V3 VARIANT
  DIAGNOSIS TEXT
  DISCOVERY VARIANT
  LAST_CUSTOMIZATION VARIANT
  LAST_SERVICE_MODIFICATION_DATETIME TIMESTAMP_NTZ
  PATCHABLE NUMBER
  PCI_FLAG NUMBER
  PUBLISHED_DATETIME TIMESTAMP_NTZ
  QID NUMBER
  SEVERITY_LEVEL NUMBER
  SOFTWARE_LIST VARIANT
  SOLUTION TEXT
  THREAT_INTELLIGENCE VARIANT
  TITLE TEXT
  VENDOR_REFERENCE_LIST VARIANT
  VULN_TYPE TEXT
}

Table PROJECTS_OVERVIEW {
  Domainname: TEXT
  Verified: TEXT
  Dmarc Added? TEXT
  DMARC set: TEXT
  SP= TEXT
  Sending? TEXT
  Sending EFD? TEXT
  number send TEXT
  Added to EFD? TEXT
  Opco? TEXT
  Contact person: TEXT
  Region: TEXT
  Assigned to: TEXT
  Unnamed: 13 TEXT
}

Table S1_VERSIONS {
  VERSION TEXT
  Release Date TEXT
  FILE TEXT
}

Table VULNERABILITIES {
  HOST_ASSET_ID NUMBER
  HOST_DNS TEXT
  HOST_ID NUMBER
  HOST_IP TEXT
  HOST_LAST_SCAN_DATETIME TIMESTAMP_NTZ
  HOST_LAST_VM_AUTH_SCANNED_DATE TIMESTAMP_NTZ
  HOST_LAST_VM_AUTH_SCANNED_DURATION NUMBER
  HOST_LAST_VM_SCANNED_DATE TIMESTAMP_NTZ
  HOST_LAST_VM_SCANNED_DURATION NUMBER
  HOST_NETBIOS TEXT
  HOST_NETWORK_ID NUMBER
  HOST_OS TEXT
  HOST_OS_CPE TEXT
  HOST_QG_HOSTID TEXT
  HOST_TRACKING_METHOD TEXT
  HOST_DNS_DATA_DOMAIN TEXT
  HOST_DNS_DATA_FQDN TEXT
  HOST_DNS_DATA_HOSTNAME TEXT
  HOST_DETECTION_LIST_DETECTION_FIRST_FOUND_DATETIME TIMESTAMP_NTZ
  HOST_DETECTION_LIST_DETECTION_FIRST_REOPENED_DATETIME TIMESTAMP_NTZ
  HOST_DETECTION_LIST_DETECTION_FQDN TEXT
  HOST_DETECTION_LIST_DETECTION_IS_DISABLED NUMBER
  HOST_DETECTION_LIST_DETECTION_IS_IGNORED NUMBER
  HOST_DETECTION_LIST_DETECTION_LAST_FIXED_DATETIME TIMESTAMP_NTZ
  HOST_DETECTION_LIST_DETECTION_LAST_FOUND_DATETIME TIMESTAMP_NTZ
  HOST_DETECTION_LIST_DETECTION_LAST_PROCESSED_DATETIME TIMESTAMP_NTZ
  HOST_DETECTION_LIST_DETECTION_LAST_REOPENED_DATETIME TIMESTAMP_NTZ
  HOST_DETECTION_LIST_DETECTION_LAST_TEST_DATETIME TIMESTAMP_NTZ
  HOST_DETECTION_LIST_DETECTION_LAST_UPDATE_DATETIME TIMESTAMP_NTZ
  HOST_DETECTION_LIST_DETECTION_PORT NUMBER
  HOST_DETECTION_LIST_DETECTION_PROTOCOL TEXT
  HOST_DETECTION_LIST_DETECTION_QID NUMBER
  HOST_DETECTION_LIST_DETECTION_RESULTS TEXT
  HOST_DETECTION_LIST_DETECTION_SEVERITY NUMBER
  HOST_DETECTION_LIST_DETECTION_SSL NUMBER
  HOST_DETECTION_LIST_DETECTION_STATUS TEXT
  HOST_DETECTION_LIST_DETECTION_TIMES_FOUND NUMBER
  HOST_DETECTION_LIST_DETECTION_TIMES_REOPENED NUMBER
  HOST_DETECTION_LIST_DETECTION_TYPE TEXT
  HOST_DETECTION_LIST_DETECTION_UNIQUE_VULN_ID NUMBER
}

Table VW_ANCON_COMPLIANCE_SETTINGS {
  PARAMETER_NAME TEXT
  PARAMETER_VALUE NUMBER
  DESCRIPTION TEXT
}

Table VW_AV_REGIONAL_TREND {
  REGION TEXT
  REPORT_MONTH DATE [not null]
  AVG_EDR_COVERAGE_PCT FLOAT
  AVG_HEALTH_SCORE FLOAT
  NON_COMPLIANT_OPCOS NUMBER
}

Table VW_BITSIGHT_CRITICAL_FINDINGS {
  DOMAIN_NAME TEXT
  VENDOR_TAGS TEXT
  RISK_VECTOR_LABEL TEXT
  CATEGORY TEXT
  FINDING TEXT
  EVIDENCE TEXT
  LAST_SEEN DATE
  SEVERITY TEXT
  RECOMMENDED_ACTION TEXT
  FINDING_STATUS TEXT
}

Table VW_DEFENDER_OS_SECURITY {
  OPERATING_SYSTEM TEXT
  OS_VERSION TEXT
  DEVICE_COUNT NUMBER
  COMPLIANT_DEVICES NUMBER
  COMPLIANCE_PCT NUMBER
  ACTIVE_DEVICES NUMBER
  LAST_REPORTED TIMESTAMP_NTZ
}

Table VW_FARRANS_COMPLIANCE_THRESHOLDS {
  PARAMETER_NAME TEXT
  PARAMETER_VALUE NUMBER
  DESCRIPTION TEXT
}

Table VW_FIXEDVULN_OS_TRENDS {
  OS TEXT
  FIX_MONTH TIMESTAMP_NTZ
  SEVERITY NUMBER
  VULNERABILITIES_FIXED NUMBER
  AVG_REMEDIATION_DAYS NUMBER
  REOPENED_COUNT NUMBER
  REOPEN_RATE_PCT NUMBER
  PREV_MONTH_COUNT NUMBER
  MONTHLY_CHANGE NUMBER
}

Table VW_HARDWARE_INVENTORY_SUMMARY {
  ORGANISATION TEXT
  TOTAL_DEVICES NUMBER
  ACTIVE_DEVICES NUMBER
  INACTIVE_DEVICES NUMBER
  STALE_RECORDS NUMBER
  ACTIVE_PERCENTAGE NUMBER
  COMPLIANCE_STATUS TEXT
}

Table VW_CROWDSTRIKE_COVERAGE {
  REPORT_DATE DATE
  ACTIVE_COUNT NUMBER [not null]
  TOTAL_ENDPOINTS NUMBER [not null]
  COVERAGE_PCT NUMBER
  GAP_TO_TARGET NUMBER
  COMPLIANCE_STATUS TEXT
  SNAPSHOT_TS TIMESTAMP_LTZ
}

Table VW_CYBELANGEL_COMPLIANCE_SETTINGS {
  PARAMETER_NAME TEXT
  PARAMETER_VALUE NUMBER
  DESCRIPTION TEXT
}

Table VW_FARRANS_INACTIVE_ALERTS {
  ENDPOINT_NAME TEXT [not null]
  OS TEXT
  PROTECTION TEXT
  HEALTH_STATUS TEXT
  LAST_ACTIVE TIMESTAMP_NTZ
  DAYS_INACTIVE NUMBER
  ALERT_SEVERITY TEXT
  ALERT_TYPE TEXT
}

Table VW_FARRANS_USER_ACTIVITY {
  LAST_USER TEXT
  ENDPOINT_COUNT NUMBER
  PROTECTED_COUNT NUMBER
  UNPROTECTED_COUNT NUMBER
  HEALTHY_COUNT NUMBER
  FIRST_ACTIVITY TIMESTAMP_NTZ
  LAST_ACTIVITY TIMESTAMP_NTZ
  DAYS_SINCE_LAST_ACTIVITY NUMBER
  PROTECTION_RATE NUMBER
}

Table VW_LEVIAT_ACCOUNT_HEALTH {
  BUSINESS_UNIT TEXT
  TOTAL_ACCOUNTS NUMBER
  LOCKED_ACCOUNTS NUMBER
  LOCKED_ACCOUNT_PCT NUMBER
  EXPIRED_PASSWORDS NUMBER
  EXPIRED_PASSWORD_PCT NUMBER
  INACTIVE_ACCOUNTS NUMBER
  INACTIVE_ACCOUNT_PCT NUMBER
  FORCE_PASSWORD_CHANGE_COUNT NUMBER
  PASSWORD_NEVER_EXPIRES_COUNT NUMBER
  SNAPSHOT_DATE DATE
}

Table VW_LICENSE_COMPLIANCE {
  ORGANISATION TEXT
  LICENSED_COUNT NUMBER
  UNLICENSED_COUNT NUMBER
  MISSING_LICENSE NUMBER
  COMPLIANCE_PERCENTAGE NUMBER
}

Table VW_QUALYS_HOST_COMPLIANCE {
  HOST_OS TEXT
  HOST_COUNT NUMBER
  COMPLIANT_HOSTS NUMBER
  NON_COMPLIANT_HOSTS NUMBER
  COMPLIANCE_PCT NUMBER
  AVG_DAYS_SINCE_SCAN NUMBER
  OUT_OF_SCOPE NUMBER
  SNAPSHOT_DATE DATE
}

Table VW_SYMANTEC_ANALYSIS {
  DATESEEN TEXT
  TYPE TEXT
  DEVICE_NAME TEXT
  USER_NAME TEXT
  FEATURE_NAME TEXT
  FILE_NAME TEXT
  THREAT_NAME TEXT
  THREAT_TYPE TEXT
  DEVICE_GROUP TEXT
  THREAT_CATEGORY TEXT
  DETECTION_CATEGORY TEXT
  OPERATING_SYSTEM TEXT
  MALWARE_PROTECTION TEXT
  DEVICE_SECURITY_STATUS TEXT
  HAS_UNRESOLVED_THREATS BOOLEAN
  GROUP_NAME TEXT
  SYMANTEC_OPCO TEXT
}

Table VW_GOLD_TRELLIX_AGENT_HEALTH {
  OPCO TEXT
  UPDATED_AGENTS NUMBER
  TOTAL_AGENTS NUMBER
  UPDATE_PCT NUMBER
  MEDIAN_DAYS_OUTDATED NUMBER
  SNAPSHOT_DATE DATE
}

Table VW_QUALYS_EXECUTIVE_SUMMARY {
  METRIC_CATEGORY TEXT
  INSCOPE_HOSTS NUMBER
  SCANNED_HOSTS NUMBER
  CRITICAL_VULNS NUMBER
  EXPLOITABLE_VULNS NUMBER
  CRITICAL_UNPATCHED NUMBER
  SNAPSHOT_DATE DATE
}

Table VW_SENTINEL_ACTIVITY_ANALYSIS {
  DOMAIN TEXT
  DEVICE_TYPE TEXT
  TOTAL_ENDPOINTS NUMBER
  ACTIVE_1D NUMBER
  ACTIVE_7D NUMBER
  ACTIVE_30D NUMBER
  INACTIVE_30D NUMBER
  ACTIVE_7D_PCT NUMBER
  AVG_DAYS_INACTIVE NUMBER
  SNAPSHOT_DATE DATE
}

Table VW_SOPHOS_ENDPOINT_HEALTH {
  SCOPE TEXT
  TOTAL_ENDPOINTS NUMBER
  HEALTHY_ENDPOINTS NUMBER
  PROTECTED_ENDPOINTS NUMBER
  ACTIVE_7D NUMBER
  HEALTH_COMPLIANCE_PCT NUMBER
  PROTECTION_COVERAGE_PCT NUMBER
  SNAPSHOT_DATE DATE
}

Table VW_ZSCALER_SECURITY_ALERTS {
  ALERT_TYPE TEXT
  DEVICE_HOSTNAME TEXT
  USER_EMAIL TEXT
  LAST_CONNECTED TIMESTAMP_NTZ
  DAYS_INACTIVE NUMBER
  DESCRIPTION TEXT
}

Table VW_BITSIGHT_RISK_TREND {
  MONTH DATE
  CATEGORY TEXT
  VENDORS_AFFECTED NUMBER
  CRITICAL_FINDINGS NUMBER
  PREV_MONTH_FINDINGS NUMBER
  MONTHLY_CHANGE NUMBER
}

Table VW_DEFENDER_AGENT_HEALTH {
  HEALTH_SCOPE TEXT
  TOTAL_DEVICES NUMBER
  HEALTHY_AGENTS NUMBER
  UNHEALTHY_AGENTS NUMBER
  UNHEALTHY_PCT NUMBER
  ACTIVE_DEVICES NUMBER
  INACTIVE_DEVICES NUMBER
  SNAPSHOT_DATE DATE
}

Table VW_DEFENDER_COMPLIANCE_THRESHOLDS {
  PARAMETER_NAME TEXT
  PARAMETER_VALUE NUMBER
  DESCRIPTION TEXT
}
