@startuml
title LANDING Layer - ITSECKPI
skinparam linetype ortho
skinparam class BackgroundColor #FF9933

class AD_COMPUTERS_ALUNGRIFFITHS {
  NAME : TEXT
  OPERATING_SYSTEM : TEXT
  LAST_LOGON_DATE : TEXT
  DISTINGUISHED_NAME : TEXT
}
class AD_COMPUTERS_AMAT {
  NAME : TEXT
  OPERATING_SYSTEM : TEXT
  LAST_LOGON_DATE : TEXT
  DISTINGUISHED_NAME : TEXT
}
class AD_COMPUTERS_ANCON {
  NAME : TEXT
  OPERATING_SYSTEM : TEXT
  LAST_LOGON_DATE : TEXT
  DISTINGUISHED_NAME : TEXT
}
class AD_COMPUTERS_APG {
  NAME : TEXT
  OPERATING_SYSTEM : TEXT
  LAST_LOGON_DATE : TEXT
  DISTINGUISHED_NAME : TEXT
}
class AD_COMPUTERS_ASHGROVE {
  NAME : TEXT
  OPERATING_SYSTEM : TEXT
  LAST_LOGON_DATE : TEXT
  DISTINGUISHED_NAME : TEXT
}
class AD_COMPUTERS_BELGIUM {
  NAME : TEXT
  OPERATING_SYSTEM : TEXT
  LAST_LOGON_DATE : TEXT
  DISTINGUISHED_NAME : TEXT
}
class AD_COMPUTERS_CRHPP_NET {
  NAME : TEXT
  OPERATING_SYSTEM : TEXT
  LAST_LOGON_DATE : TEXT
  DISTINGUISHED_NAME : TEXT
}
class AD_COMPUTERS_CRH_CORP {
  NAME : TEXT
  OPERATING_SYSTEM : TEXT
  LAST_LOGON_DATE : TEXT
  DISTINGUISHED_NAME : TEXT
}
class AD_COMPUTERS_CRH_NET {
  NAME : TEXT
  OPERATING_SYSTEM : TEXT
  LAST_LOGON_DATE : TEXT
  DISTINGUISHED_NAME : TEXT
}
class AD_COMPUTERS_CRH_UNI_COM {
  NAME : TEXT
  OPERATING_SYSTEM : TEXT
  LAST_LOGON_DATE : TEXT
  DISTINGUISHED_NAME : TEXT
}
class AD_COMPUTERS_DD_MM_YYYY {
  NAME : TEXT
  OPERATING_SYSTEM : TEXT
  LAST_LOGON_DATE : TEXT
  DISTINGUISHED_NAME : TEXT
  SOURCE_NAME : TEXT
}
class AD_COMPUTERS_DENMARK {
  NAME : TEXT
  OPERATING_SYSTEM : TEXT
  LAST_LOGON_DATE : TEXT
  DISTINGUISHED_NAME : TEXT
}
class AD_COMPUTERS_DEV_CRH_UNI_NET {
  NAME : TEXT
  OPERATING_SYSTEM : TEXT
  LAST_LOGON_DATE : TEXT
  DISTINGUISHED_NAME : TEXT
}
class AD_COMPUTERS_EMAT {
  NAME : TEXT
  OPERATING_SYSTEM : TEXT
  LAST_LOGON_DATE : TEXT
  DISTINGUISHED_NAME : TEXT
}
class AD_COMPUTERS_EMAT_CRHPP_NET {
  NAME : TEXT
  OPERATING_SYSTEM : TEXT
  LAST_LOGON_DATE : TEXT
  DISTINGUISHED_NAME : TEXT
}
class AD_COMPUTERS_EMAT_HCL {
  DOMAIN_NAME : TEXT
  OU : TEXT
  NAME : TEXT
  SAMACCOUNTNAME : TEXT
  OPERATINGSYSTEM : TEXT
  IPV4ADDRESS : TEXT
  DNSHOSTNAME : TEXT
  DESCRIPTION : TEXT
  DISTINGUISHEDNAME : TEXT
  ENABLED : TEXT
  WHENCREATED : TEXT
  WHENCHANGED : TEXT
  PWDLASTSET : TEXT
  LASTLOGONDATE : TEXT
  SOURCE_NAME : TEXT
}
class AD_COMPUTERS_EU_CRH_CORP_NET {
  NAME : TEXT
  OPERATING_SYSTEM : TEXT
  LAST_LOGON_DATE : TEXT
  DISTINGUISHED_NAME : TEXT
}
class AD_COMPUTERS_FERROBETON_COMPUTE {
  NAME : TEXT
  OPERATING_SYSTEM : TEXT
  LAST_LOGON_DATE : TEXT
  DISTINGUISHED_NAME : TEXT
}
class AD_COMPUTERS_FERROBETON_SERVERS {
  NAME : TEXT
  OPERATING_SYSTEM : TEXT
  LAST_LOGON_DATE : TEXT
  DISTINGUISHED_NAME : TEXT
}
class AD_COMPUTERS_LEVIAT {
  NAME : TEXT
  OPERATING_SYSTEM : TEXT
  LAST_LOGON_DATE : TEXT
  DISTINGUISHED_NAME : TEXT
}
BOL_CROWDSTRIKE --> DIM_HOST
BOL_CROWDSTRIKE --> HOSTS
BOL_CROWDSTRIKE --> HOSTS_1
BOL_CROWDSTRIKE --> HOSTS_copy2
BOL_CROWDSTRIKE --> HOSTS_old
BOL_CROWDSTRIKE_OLD --> DIM_HOST
BOL_CROWDSTRIKE_OLD --> HOSTS
BOL_CROWDSTRIKE_OLD --> HOSTS_1
BOL_CROWDSTRIKE_OLD --> HOSTS_copy2
BOL_CROWDSTRIKE_OLD --> HOSTS_old
CROWDSTRIKE --> DIM_HOST
CROWDSTRIKE --> HOSTS
CROWDSTRIKE --> HOSTS_1
CROWDSTRIKE --> HOSTS_copy2
CROWDSTRIKE --> HOSTS_old
DEFENDERAV --> COPY_OF_MASTER_DEVICE_INTEGRITY
DEFENDERAV --> SYMANTEC_DEVICE
DEFENDERAV_OLD --> COPY_OF_MASTER_DEVICE_INTEGRITY
DEFENDERAV_OLD --> SYMANTEC_DEVICE
DEFENDER_THREATS_ARCHIVE --> CYBELANGELALERTS
DEFENDER_THREATS_ARCHIVE --> SPLUNK_ALERTS
DEFENDER_THREATS_ARCHIVE --> ZEROFOXALERTS
DEFENDER_THREATS_LANDING --> CYBELANGELALERTS
DEFENDER_THREATS_LANDING --> SPLUNK_ALERTS
DEFENDER_THREATS_LANDING --> ZEROFOXALERTS
DIM_HOST --> DIM_HOST
DIM_HOST --> HOSTS
DIM_HOST --> HOSTS_1
DIM_HOST --> HOSTS_copy2
DIM_HOST --> HOSTS_old
DIM_VULNERABILITY --> DIM_VULNERABILITY
DIM_VULNERABILITY --> FACT_VULN_SCAN
DIM_VULNERABILITY --> FIXEDVULNERABILITIES
DIM_VULNERABILITY --> FIXEDVULNERABILITIES_1
DIM_VULNERABILITY --> FIXEDVULNERABILITIES_old
DIM_VULNERABILITY --> TOTAL_VULNERABILITIES
DIM_VULNERABILITY --> TOTAL_VULNERABILITIES_EXPLOITABLE
DIM_VULNERABILITY --> VULNERABILITIES
DIM_VULNERABILITY --> VULNERABILITIES_1
DIM_VULNERABILITY --> VULNERABILITIES_old
FACT_LEVIAT_SECURITY_EVENTS --> FACT_LEVIAT_SECURITY_EVENTS
FACT_LEVIAT_SECURITY_EVENTS --> THREAT_INTEL_EVENTS
FACT_VULN_SCAN --> FACT_VULN_SCAN
FACT_VULN_SCAN --> DIM_VULNERABILITY
FACT_VULN_SCAN --> FACT_VULN_SCAN
FACT_VULN_SCAN --> FIXEDVULNERABILITIES
FACT_VULN_SCAN --> FIXEDVULNERABILITIES_1
FACT_VULN_SCAN --> FIXEDVULNERABILITIES_old
FACT_VULN_SCAN --> TOTAL_VULNERABILITIES
PROOFPOINT_MESSAGE_LOGS --> PROOFPOINT_MESSAGE_LOGS
VULNERABILITIES --> DIM_HOST
VULNERABILITIES --> HOSTS
VULNERABILITIES --> HOSTS_1
VULNERABILITIES --> HOSTS_copy2
VULNERABILITIES --> HOSTS_old
VULNERABILITIES_1 --> DIM_HOST
VULNERABILITIES_1 --> HOSTS
VULNERABILITIES_1 --> HOSTS_1
VULNERABILITIES_1 --> HOSTS_copy2
VULNERABILITIES_1 --> HOSTS_old
VULNERABILITIES_old --> DIM_HOST
VULNERABILITIES_old --> HOSTS
VULNERABILITIES_old --> HOSTS_1
VULNERABILITIES_old --> HOSTS_copy2
VULNERABILITIES_old --> HOSTS_old
ZEROFOXALERTS --> CYBELANGELALERTS
ZEROFOXALERTS --> SPLUNK_ALERTS
ZEROFOXALERTS --> ZEROFOXALERTS
@enduml