-- =====================================================
-- SCRIPT PARA EXTRAER METADATA DEL ESQUEMA SECURITY_ANALYTICS
-- =====================================================
-- Ejecuta este script en tu sesión activa de Snowflake en VS Code
-- Luego copia los resultados para generar el ERD

-- 1. CONFIGURAR CONTEXTO
USE ROLE ACCOUNTADMIN; -- O el rol que tengas permisos
USE WAREHOUSE COMPUTE_WH; -- Tu warehouse

-- =====================================================
-- PARTE 1: EXPLORAR DEV_LANDING
-- =====================================================
USE DATABASE DEV_LANDING;
USE SCHEMA SECURITY_ANALYTICS;

SELECT '=== DEV_LANDING.SECURITY_ANALYTICS TABLES ===' AS SECTION;

-- Listar todas las tablas y views
SELECT
    'DEV_LANDING' as DATABASE_NAME,
    'SECURITY_ANALYTICS' as SCHEMA_NAME,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    BYTES,
    COMMENT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
ORDER BY TABLE_NAME;

-- Obtener columnas de todas las tablas
SELECT
    'DEV_LANDING' as DATABASE_NAME,
    'SECURITY_ANALYTICS' as SCHEMA_NAME,
    TABLE_NAME,
    ORDINAL_POSITION,
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE,
    IS_NULLABLE,
    COLUMN_DEFAULT,
    COMMENT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- =====================================================
-- PARTE 2: EXPLORAR DEV_TRANSFORMATION
-- =====================================================
USE DATABASE DEV_TRANSFORMATION;
USE SCHEMA SECURITY_ANALYTICS;

SELECT '=== DEV_TRANSFORMATION.SECURITY_ANALYTICS TABLES ===' AS SECTION;

-- Listar todas las tablas y views
SELECT
    'DEV_TRANSFORMATION' as DATABASE_NAME,
    'SECURITY_ANALYTICS' as SCHEMA_NAME,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    BYTES,
    COMMENT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
ORDER BY TABLE_NAME;

-- Obtener columnas de todas las tablas
SELECT
    'DEV_TRANSFORMATION' as DATABASE_NAME,
    'SECURITY_ANALYTICS' as SCHEMA_NAME,
    TABLE_NAME,
    ORDINAL_POSITION,
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE,
    IS_NULLABLE,
    COLUMN_DEFAULT,
    COMMENT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- =====================================================
-- PARTE 3: EXPLORAR DEV_REPORTING
-- =====================================================
USE DATABASE DEV_REPORTING;
USE SCHEMA SECURITY_ANALYTICS;

SELECT '=== DEV_REPORTING.SECURITY_ANALYTICS TABLES ===' AS SECTION;

-- Listar todas las tablas y views
SELECT
    'DEV_REPORTING' as DATABASE_NAME,
    'SECURITY_ANALYTICS' as SCHEMA_NAME,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    BYTES,
    COMMENT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
ORDER BY TABLE_NAME;

-- Obtener columnas de todas las tablas
SELECT
    'DEV_REPORTING' as DATABASE_NAME,
    'SECURITY_ANALYTICS' as SCHEMA_NAME,
    TABLE_NAME,
    ORDINAL_POSITION,
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE,
    IS_NULLABLE,
    COLUMN_DEFAULT,
    COMMENT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- =====================================================
-- PARTE 4: BUSCAR FOREIGN KEYS Y CONSTRAINTS
-- =====================================================

-- Revisar constraints en las 3 bases de datos
SELECT
    rc.CONSTRAINT_CATALOG as DATABASE_NAME,
    rc.CONSTRAINT_SCHEMA as SCHEMA_NAME,
    tc.TABLE_NAME,
    tc.CONSTRAINT_NAME,
    tc.CONSTRAINT_TYPE,
    kcu.COLUMN_NAME,
    rc.UNIQUE_CONSTRAINT_NAME,
    rc.MATCH_OPTION,
    rc.UPDATE_RULE,
    rc.DELETE_RULE
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
    ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
    AND tc.TABLE_SCHEMA = kcu.TABLE_SCHEMA
    AND tc.TABLE_CATALOG = kcu.TABLE_CATALOG
LEFT JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
    ON tc.CONSTRAINT_NAME = rc.CONSTRAINT_NAME
    AND tc.TABLE_SCHEMA = rc.CONSTRAINT_SCHEMA
    AND tc.TABLE_CATALOG = rc.CONSTRAINT_CATALOG
WHERE tc.TABLE_SCHEMA = 'SECURITY_ANALYTICS'
  AND tc.TABLE_CATALOG IN ('DEV_LANDING', 'DEV_TRANSFORMATION', 'DEV_REPORTING')
ORDER BY tc.TABLE_CATALOG, tc.TABLE_NAME, tc.CONSTRAINT_NAME;

-- =====================================================
-- PARTE 5: QUERY CONSOLIDADA (ALTERNATIVA)
-- =====================================================
-- Esta query te da toda la info en una sola tabla

WITH all_tables AS (
    SELECT
        TABLE_CATALOG as DATABASE_NAME,
        TABLE_SCHEMA as SCHEMA_NAME,
        TABLE_NAME,
        TABLE_TYPE,
        ROW_COUNT,
        COMMENT
    FROM DEV_LANDING.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'

    UNION ALL

    SELECT
        TABLE_CATALOG,
        TABLE_SCHEMA,
        TABLE_NAME,
        TABLE_TYPE,
        ROW_COUNT,
        COMMENT
    FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'

    UNION ALL

    SELECT
        TABLE_CATALOG,
        TABLE_SCHEMA,
        TABLE_NAME,
        TABLE_TYPE,
        ROW_COUNT,
        COMMENT
    FROM DEV_REPORTING.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
)
SELECT * FROM all_tables
ORDER BY DATABASE_NAME, TABLE_NAME;

-- =====================================================
-- PARTE 6: ANÁLISIS DE RELACIONES POR NOMBRES
-- =====================================================
-- Buscar columnas que parecen ser FKs por su nombre

WITH potential_fks AS (
    SELECT
        TABLE_CATALOG as DATABASE_NAME,
        TABLE_NAME,
        COLUMN_NAME,
        DATA_TYPE
    FROM DEV_LANDING.INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
      AND (COLUMN_NAME LIKE '%_ID'
           OR COLUMN_NAME LIKE '%_KEY'
           OR COLUMN_NAME LIKE '%_CODE'
           OR COLUMN_NAME LIKE '%_SK'
           OR COLUMN_NAME LIKE '%_FK')

    UNION ALL

    SELECT
        TABLE_CATALOG,
        TABLE_NAME,
        COLUMN_NAME,
        DATA_TYPE
    FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
      AND (COLUMN_NAME LIKE '%_ID'
           OR COLUMN_NAME LIKE '%_KEY'
           OR COLUMN_NAME LIKE '%_CODE'
           OR COLUMN_NAME LIKE '%_SK'
           OR COLUMN_NAME LIKE '%_FK')

    UNION ALL

    SELECT
        TABLE_CATALOG,
        TABLE_NAME,
        COLUMN_NAME,
        DATA_TYPE
    FROM DEV_REPORTING.INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
      AND (COLUMN_NAME LIKE '%_ID'
           OR COLUMN_NAME LIKE '%_KEY'
           OR COLUMN_NAME LIKE '%_CODE'
           OR COLUMN_NAME LIKE '%_SK'
           OR COLUMN_NAME LIKE '%_FK')
)
SELECT
    DATABASE_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    REGEXP_REPLACE(COLUMN_NAME, '(_ID|_KEY|_CODE|_SK|_FK)$', '') as POSSIBLE_REFERENCE_TABLE
FROM potential_fks
ORDER BY DATABASE_NAME, TABLE_NAME, COLUMN_NAME;