-- Verify ServiceNow setup is complete

USE DATABASE DEV_TRANSFORMATION;
USE SCHEMA SERVICENOW;

-- List all tables
SHOW TABLES IN SCHEMA DEV_TRANSFORMATION.SERVICENOW;

-- Verify configuration
SELECT * FROM CONNECTOR_CONFIG ORDER BY table_name;

-- Switch to reporting
USE DATABASE DEV_REPORTING;
USE SCHEMA SERVICENOW;

-- List all views
SHOW VIEWS IN SCHEMA DEV_REPORTING.SERVICENOW;

-- Summary
SELECT
    'DEV_TRANSFORMATION.SERVICENOW' AS layer,
    'Tables' AS object_type,
    COUNT(*) AS count
FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES
WHERE table_schema = 'SERVICENOW'

UNION ALL

SELECT
    'DEV_REPORTING.SERVICENOW' AS layer,
    'Views' AS object_type,
    COUNT(*) AS count
FROM DEV_REPORTING.INFORMATION_SCHEMA.VIEWS
WHERE table_schema = 'SERVICENOW';
