-- ============================================================
-- ANÁLISIS ALTERNATIVO DEL MODELO DE DATOS SECURITY_ANALYTICS
-- Script SQL para ejecutar directamente en Snowflake
-- ============================================================

-- 1. ANÁLISIS DE TABLAS SIN DATOS (Potencialmente mal configuradas)
-- ============================================================
USE DATABASE DEV_LANDING;
USE SCHEMA SECURITY_ANALYTICS;

SELECT
    'DEV_LANDING' as DATABASE_NAME,
    TABLE_NAME,
    ROW_COUNT,
    BYTES,
    CREATED,
    CASE
        WHEN ROW_COUNT = 0 THEN 'EMPTY TABLE - CHECK ETL'
        WHEN ROW_COUNT < 100 THEN 'LOW VOLUME - VERIFY SOURCE'
        ELSE 'OK'
    END as STATUS
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND TABLE_TYPE = 'BASE TABLE'
ORDER BY ROW_COUNT;

-- 2. ANÁLISIS DE MODELO DIMENSIONAL EN TRANSFORMATION
-- ============================================================
USE DATABASE DEV_TRANSFORMATION;
USE SCHEMA SECURITY_ANALYTICS;

-- 2.1 Verificar Dimensiones
SELECT
    'DIMENSIONS' as OBJECT_TYPE,
    TABLE_NAME,
    ROW_COUNT,
    CASE
        WHEN ROW_COUNT = 0 THEN 'EMPTY - NEEDS LOAD'
        WHEN ROW_COUNT < 100 THEN 'SMALL DIM'
        WHEN ROW_COUNT < 10000 THEN 'MEDIUM DIM'
        ELSE 'LARGE DIM'
    END as SIZE_CATEGORY,
    COMMENT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND TABLE_TYPE = 'BASE TABLE'
AND (TABLE_NAME LIKE 'DIM_%' OR TABLE_NAME LIKE 'D_%')
ORDER BY ROW_COUNT DESC;

-- 2.2 Verificar Facts
SELECT
    'FACTS' as OBJECT_TYPE,
    TABLE_NAME,
    ROW_COUNT,
    CASE
        WHEN ROW_COUNT = 0 THEN 'EMPTY - CHECK ETL PIPELINE'
        WHEN ROW_COUNT < 1000 THEN 'LOW VOLUME'
        WHEN ROW_COUNT < 100000 THEN 'MEDIUM VOLUME'
        ELSE 'HIGH VOLUME'
    END as VOLUME_CATEGORY,
    COMMENT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND TABLE_TYPE = 'BASE TABLE'
AND (TABLE_NAME LIKE 'FACT_%' OR TABLE_NAME LIKE 'FCT_%' OR TABLE_NAME LIKE 'F_%')
ORDER BY ROW_COUNT DESC;

-- 3. ANÁLISIS DE COLUMNAS _ID, _KEY (Potenciales FKs sin constraint)
-- ============================================================

-- 3.1 En Facts - Identificar FKs potenciales
SELECT
    t.TABLE_NAME,
    c.COLUMN_NAME,
    c.DATA_TYPE,
    c.IS_NULLABLE,
    CASE
        WHEN c.COLUMN_NAME LIKE '%_ID' THEN 'POTENTIAL FK'
        WHEN c.COLUMN_NAME LIKE '%_KEY' THEN 'POTENTIAL FK'
        WHEN c.COLUMN_NAME LIKE '%_SK' THEN 'SURROGATE KEY'
        WHEN c.COLUMN_NAME LIKE '%DATE%' THEN 'DATE DIM CANDIDATE'
        ELSE 'CHECK'
    END as KEY_TYPE,
    -- Intentar encontrar la dimensión correspondiente
    CASE
        WHEN c.COLUMN_NAME LIKE '%USER%' THEN 'DIM_USER/DIM_ANCON_USERS'
        WHEN c.COLUMN_NAME LIKE '%DATE%' THEN 'DIM_DATES'
        WHEN c.COLUMN_NAME LIKE '%HOST%' THEN 'DIM_HOST'
        WHEN c.COLUMN_NAME LIKE '%DEVICE%' THEN 'DIM_SNOW_DEVICES'
        WHEN c.COLUMN_NAME LIKE '%ENDPOINT%' THEN 'DIM_DEFENDER_ENDPOINTS'
        WHEN c.COLUMN_NAME LIKE '%VULNERABILIT%' THEN 'DIM_FIXED_VULNERABILITIES'
        ELSE 'NO DIM FOUND - CREATE?'
    END as SUGGESTED_DIM
FROM INFORMATION_SCHEMA.TABLES t
JOIN INFORMATION_SCHEMA.COLUMNS c
    ON t.TABLE_NAME = c.TABLE_NAME
    AND t.TABLE_SCHEMA = c.TABLE_SCHEMA
WHERE t.TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND t.TABLE_TYPE = 'BASE TABLE'
AND t.TABLE_NAME LIKE 'FACT_%'
AND (
    c.COLUMN_NAME LIKE '%_ID' OR
    c.COLUMN_NAME LIKE '%_KEY' OR
    c.COLUMN_NAME LIKE '%_SK' OR
    c.COLUMN_NAME LIKE '%_DATE'
)
ORDER BY t.TABLE_NAME, c.ORDINAL_POSITION;

-- 4. DETECTAR TABLAS QUE NO SIGUEN EL MODELO DIMENSIONAL
-- ============================================================
SELECT
    'NON_DIMENSIONAL' as ISSUE,
    TABLE_NAME,
    ROW_COUNT,
    'Should be renamed to DIM_/FACT_/STG_' as RECOMMENDATION
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND TABLE_TYPE = 'BASE TABLE'
AND TABLE_NAME NOT LIKE 'DIM_%'
AND TABLE_NAME NOT LIKE 'FACT_%'
AND TABLE_NAME NOT LIKE 'FCT_%'
AND TABLE_NAME NOT LIKE 'STG_%'
AND TABLE_NAME NOT LIKE 'HIST_%'
AND TABLE_NAME NOT LIKE 'VW_%'
AND TABLE_NAME NOT LIKE 'V_%'
ORDER BY ROW_COUNT DESC;

-- 5. ANÁLISIS DE RELACIONES ENTRE CAPAS
-- ============================================================

-- 5.1 Tablas en Landing sin correspondencia en Transformation
WITH landing_tables AS (
    SELECT TABLE_NAME
    FROM DEV_LANDING.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
    AND TABLE_TYPE = 'BASE TABLE'
),
transformation_tables AS (
    SELECT TABLE_NAME
    FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
)
SELECT
    l.TABLE_NAME as LANDING_TABLE,
    'NO TRANSFORMATION' as ISSUE,
    'Create ETL pipeline to Transformation layer' as ACTION_NEEDED
FROM landing_tables l
WHERE NOT EXISTS (
    SELECT 1
    FROM transformation_tables t
    WHERE UPPER(t.TABLE_NAME) LIKE '%' || REPLACE(REPLACE(UPPER(l.TABLE_NAME), 'RAW_', ''), 'STG_', '') || '%'
)
LIMIT 20;

-- 6. VALIDACIÓN DE COLUMNAS CRÍTICAS
-- ============================================================

-- 6.1 Facts sin columnas de fecha (necesarias para análisis temporal)
SELECT
    TABLE_NAME,
    'NO DATE COLUMNS' as ISSUE,
    'Add date dimension key' as RECOMMENDATION
FROM INFORMATION_SCHEMA.TABLES t
WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
AND TABLE_TYPE = 'BASE TABLE'
AND TABLE_NAME LIKE 'FACT_%'
AND NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS c
    WHERE c.TABLE_NAME = t.TABLE_NAME
    AND c.TABLE_SCHEMA = t.TABLE_SCHEMA
    AND (c.COLUMN_NAME LIKE '%DATE%' OR c.COLUMN_NAME LIKE '%_DT')
);

-- 7. VERIFICAR UNICIDAD DE DATOS (Detectar duplicados potenciales)
-- ============================================================

-- Ejemplo para una tabla específica (ajustar según necesidad)
-- Esta query identifica columnas que podrían ser Primary Key
/*
SELECT
    'CHECK_UNIQUENESS' as ANALYSIS,
    TABLE_NAME,
    COLUMN_NAME,
    COUNT(DISTINCT COLUMN_VALUE) as DISTINCT_VALUES,
    COUNT(*) as TOTAL_ROWS,
    CASE
        WHEN COUNT(DISTINCT COLUMN_VALUE) = COUNT(*) THEN 'UNIQUE - PK CANDIDATE'
        WHEN COUNT(DISTINCT COLUMN_VALUE) > COUNT(*) * 0.95 THEN 'MOSTLY UNIQUE'
        ELSE 'NOT UNIQUE'
    END as UNIQUENESS_STATUS
FROM (
    -- Necesitarías ejecutar esto para cada tabla/columna de interés
    SELECT
        'YOUR_TABLE' as TABLE_NAME,
        'YOUR_COLUMN' as COLUMN_NAME,
        YOUR_COLUMN as COLUMN_VALUE
    FROM YOUR_TABLE
)
GROUP BY TABLE_NAME, COLUMN_NAME;
*/

-- 8. RESUMEN DE PROBLEMAS CRÍTICOS
-- ============================================================

WITH issues_summary AS (
    -- Tablas vacías en Facts
    SELECT
        'EMPTY_FACTS' as ISSUE_TYPE,
        COUNT(*) as ISSUE_COUNT,
        'Critical' as SEVERITY
    FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
    AND TABLE_TYPE = 'BASE TABLE'
    AND TABLE_NAME LIKE 'FACT_%'
    AND ROW_COUNT = 0

    UNION ALL

    -- Tablas vacías en Dimensions
    SELECT
        'EMPTY_DIMS' as ISSUE_TYPE,
        COUNT(*) as ISSUE_COUNT,
        'High' as SEVERITY
    FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
    AND TABLE_TYPE = 'BASE TABLE'
    AND TABLE_NAME LIKE 'DIM_%'
    AND ROW_COUNT = 0

    UNION ALL

    -- Tablas sin nomenclatura estándar
    SELECT
        'NON_STANDARD_NAMING' as ISSUE_TYPE,
        COUNT(*) as ISSUE_COUNT,
        'Medium' as SEVERITY
    FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'SECURITY_ANALYTICS'
    AND TABLE_TYPE = 'BASE TABLE'
    AND TABLE_NAME NOT LIKE 'DIM_%'
    AND TABLE_NAME NOT LIKE 'FACT_%'
    AND TABLE_NAME NOT LIKE 'STG_%'
)
SELECT * FROM issues_summary
ORDER BY
    CASE SEVERITY
        WHEN 'Critical' THEN 1
        WHEN 'High' THEN 2
        WHEN 'Medium' THEN 3
        ELSE 4
    END;

-- 9. GENERAR RECOMENDACIONES DE DDL
-- ============================================================

-- 9.1 Sugerir creación de Primary Keys
SELECT
    'ALTER TABLE ' || TABLE_NAME || ' ADD PRIMARY KEY (' || COLUMN_NAME || ');' as SUGGESTED_DDL,
    'Add PK to ' || TABLE_NAME as DESCRIPTION
FROM (
    SELECT DISTINCT
        t.TABLE_NAME,
        c.COLUMN_NAME
    FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES t
    JOIN DEV_TRANSFORMATION.INFORMATION_SCHEMA.COLUMNS c
        ON t.TABLE_NAME = c.TABLE_NAME
        AND t.TABLE_SCHEMA = c.TABLE_SCHEMA
    WHERE t.TABLE_SCHEMA = 'SECURITY_ANALYTICS'
    AND t.TABLE_TYPE = 'BASE TABLE'
    AND t.TABLE_NAME LIKE 'DIM_%'
    AND (c.COLUMN_NAME = 'ID' OR c.COLUMN_NAME = t.TABLE_NAME || '_ID' OR c.COLUMN_NAME LIKE '%_KEY')
    AND c.ORDINAL_POSITION = 1
)
LIMIT 10;

-- 9.2 Sugerir creación de Foreign Keys
SELECT
    'ALTER TABLE ' || f.TABLE_NAME || ' ADD FOREIGN KEY (' || f.COLUMN_NAME || ') REFERENCES ' ||
    CASE
        WHEN f.COLUMN_NAME LIKE '%USER%' THEN 'DIM_ANCON_USERS(USER_ID)'
        WHEN f.COLUMN_NAME LIKE '%DATE%' THEN 'DIM_DATES(DATE_KEY)'
        WHEN f.COLUMN_NAME LIKE '%HOST%' THEN 'DIM_HOST(HOST_ID)'
        ELSE 'DIM_TABLE(KEY_COLUMN)'
    END || ';' as SUGGESTED_DDL,
    'Add FK from ' || f.TABLE_NAME || '.' || f.COLUMN_NAME as DESCRIPTION
FROM (
    SELECT
        t.TABLE_NAME,
        c.COLUMN_NAME
    FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES t
    JOIN DEV_TRANSFORMATION.INFORMATION_SCHEMA.COLUMNS c
        ON t.TABLE_NAME = c.TABLE_NAME
        AND t.TABLE_SCHEMA = c.TABLE_SCHEMA
    WHERE t.TABLE_SCHEMA = 'SECURITY_ANALYTICS'
    AND t.TABLE_TYPE = 'BASE TABLE'
    AND t.TABLE_NAME LIKE 'FACT_%'
    AND (c.COLUMN_NAME LIKE '%_ID' OR c.COLUMN_NAME LIKE '%_KEY')
) f
LIMIT 10;