/*
================================================================================
Discover Proofpoint Tables - Find exact location
================================================================================
*/

USE ROLE DEV_DEVELOPER;
USE WAREHOUSE DEV_WH;

-- Search for Proofpoint tables in all databases and schemas
SELECT
    TABLE_CATALOG as DATABASE_NAME,
    TABLE_SCHEMA as SCHEMA_NAME,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    CREATED
FROM DEV_LANDING.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%PROOFPOINT%'
UNION ALL
SELECT
    TABLE_CATALOG as DATABASE_NAME,
    TABLE_SCHEMA as SCHEMA_NAME,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    CREATED
FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%PROOFPOINT%'
UNION ALL
SELECT
    TABLE_CATALOG as DATABASE_NAME,
    TABLE_SCHEMA as SCHEMA_NAME,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    CREATED
FROM DEV_REPORTING.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%PROOFPOINT%'
ORDER BY DATABASE_NAME, SCHEMA_NAME, TABLE_NAME;
