/*
================================================================================
Discover ALL Service Tables - Complete mapping
================================================================================
*/

USE ROLE DEV_DEVELOPER;
USE WAREHOUSE DEV_WH;

-- Search for ALL service tables across all databases
SELECT
    'SentinelOne' as SERVICE_NAME,
    TABLE_CATALOG as DATABASE_NAME,
    TABLE_SCHEMA as SCHEMA_NAME,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    CREATED
FROM DEV_LANDING.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%SENTINEL%'
UNION ALL
SELECT
    'SentinelOne',
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    CREATED
FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%SENTINEL%'

UNION ALL

SELECT
    'CybelAngel',
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    CREATED
FROM DEV_LANDING.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%CYBELANGEL%'
UNION ALL
SELECT
    'CybelAngel',
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    CREATED
FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%CYBELANGEL%'

UNION ALL

SELECT
    'Leviat',
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    CREATED
FROM DEV_LANDING.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%LEVIAT%'
UNION ALL
SELECT
    'Leviat',
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    CREATED
FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%LEVIAT%'

UNION ALL

SELECT
    'Proofpoint',
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    CREATED
FROM DEV_LANDING.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%PROOFPOINT%'
UNION ALL
SELECT
    'Proofpoint',
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    CREATED
FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%PROOFPOINT%'

UNION ALL

SELECT
    'ServiceNow',
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    CREATED
FROM DEV_LANDING.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME IN ('SNOW') OR TABLE_NAME LIKE '%SERVICENOW%'
UNION ALL
SELECT
    'ServiceNow',
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    CREATED
FROM DEV_TRANSFORMATION.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME IN ('SNOW') OR TABLE_NAME LIKE '%SERVICENOW%'

ORDER BY SERVICE_NAME, DATABASE_NAME, SCHEMA_NAME, TABLE_NAME;
